### ISSUE TITLE
Replace kwriteconfig5 with a custom tool

### ISSUE THREAD

**Issue by pjones** [nix-community/plasma-manager#1]
The `kwriteconfig5` tool is how we currently update settings in KDE configuration files.  However:

  1. It can only update one setting at a time.  Trying to update a bunch of settings is slow.

  2. Some settings (e.g., `khotkeysrc`) use section numbers and therefore we need some way to remove old sections.

We probably need a custom tool written in C++ that can merge entire files as once.  Probably from a JSON source which Nix can generate.

**Comment by pjones** [comment]
If anyone is interested in helping, I have [a branch](https://github.com/pjones/kconfig/tree/pjones/force) of `kconfig` that allows us to edit KDE config files with a single command, instead of having to use `kwriteconfig`.

There's [a branch](https://github.com/pjones/plasma-manager/tree/pjones/kconf) of this repo that brings in my custom `kconfig` in the `flake.nix`.  However, I haven't made any of the necessary changes to actually switch to `kconfig`.

**Comment by nazarewk** [comment]
Looking through the docs we could simply manage own directory (adding/prepending it to `$KDEDIRS`) with configuration files render through Nix without any external tool?

- https://userbase.kde.org/KDE_System_Administration/Configuration_Files
- https://userbase.kde.org/KDE_System_Administration/KDE_Filesystem_Hierarchy

**Comment by toast003** [comment]
We have had our own tool for this since https://github.com/pjones/plasma-manager/pull/39
