### ISSUE TITLE
For key "Exec" in group contains an invalid field code "%a"

### ISSUE THREAD

**Issue by TimekillerTK** [nix-community/plasma-manager#105]
After solving https://github.com/pjones/plasma-manager/issues/103 - I've come across a new, different issue, which has to do with the `command` string I'm using for a hotkey:

```nix
    hotkeys.commands."alacritty-dropdown" = {
      name = "Launch Alacritty";
      key = "Alt+Space";
      command = "tdrop -a -h 90% alacritty";
    };
```

Error is:

```sh
error: builder for '/nix/store/dn5f2j2dbcfga84xwm9mzlc3cb2z3623-plasma-manager-commands.desktop.drv' failed with exit code 1;
       last 1 log lines:
       > /nix/store/yli5k9b9vrnf3cg6jjjckzshdbh0y8mi-plasma-manager-commands.desktop/share/applications/plasma-manager-commands.desktop: error: value "/nix/store/dzp7d4k1d94s1x49p9171mvcsfyxr7bj-systemd-254.6/bin/systemd-cat --identifier=plasma-manager-commands-alacritty-dropdown  tdrop -a -h 90% alacritty" for key "Exec" in group "Desktop Action alacritty-dropdown" contains an invalid field code "%a"
       For full logs, run 'nix log /nix/store/dn5f2j2dbcfga84xwm9mzlc3cb2z3623-plasma-manager-commands.desktop.drv'.
error: 1 dependencies of derivation '/nix/store/k0v7b7zs5vakpws67rcxq6q6ksd3q1rn-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qswlsl2a5dm9iwgf4bl3skrq0s75f9bz-home-manager-generation.drv' failed to build

```

Trying to escape the `%` with `\` doesn't seem to work. 

Full nix config is here (linked to offending line in question: https://github.com/TimekillerTK/nix-test/blob/dev/home/tk/beltanimal.nix#L73

**Comment by magnouvean** [comment]
It appears that escaping normally in nix doesn't work as this is using systemd syntax, and the % must be escaped in systemd syntax. You should be able to escape % with %%. Try this and let me know if it works. I got it working on my end anyway. We could consider adding code to escape it automatically though.

**Comment by TimekillerTK** [comment]
It manages to build successfully with `%%`, but that somehow results in two `%` being passed to the `tdrop` command on hotkey press:

![image](https://github.com/pjones/plasma-manager/assets/38417175/237c6c3c-e3b4-4204-b905-2e1e203c9160)

You can replicate this behavior by running the command in a terminal - it runs with a syntax error, but causes the position of the window to be reset:

```
> tdrop -a -h 90%% alacritty
2024-03-31 08:44:54 Debug command: tdrop -a -h 90%% alacritty
gawk: cmd. line:1: BEGIN {printf("%.0f", 0.01*90%*1600)}
gawk: cmd. line:1:                               ^ syntax error
/nix/store/ik4mnsdny18wczp5iij57z16n52jfwjb-tdrop-0.5.0/bin/.tdrop-wrapped: line 892: /tmp/tdrop_tk_:0/auto_hidden/wid: No such file or directory
```

> We could consider adding code to escape it automatically though.

I think that's a really good idea.

**Comment by TimekillerTK** [comment]
To clarify, while doing `%%` solves the build issue, it doesn't resolve the problem because the command receives both `%` somehow.

**Comment by magnouvean** [comment]
I can't really reproduce. Are you sure the error is caused by there being two % in the command. I can't really get tdrop to set the height anyway. When runnning the following for example:
```nix
  hotkeys.commands."demo-percent-in-command" = {
    name = "Demo";
    key = "Meta+O";
    command = ''konsole -e bash -c "echo 95%% && sleep 2"'';
  };
```
I get out a window where "95%" is displayed indicating there isn't any problem with two % being sent in. I probably will add code to automatically escape % though, I think that would be a better solution than what we have now anyway.

**Comment by TimekillerTK** [comment]
I tired your exact example: https://github.com/TimekillerTK/nix-test/commit/a653b189b57137867689dcd65be50170d51b1748

The issue still occurs on my end; hitting `Meta+O` causes a konsole window to flash on my screen for a fraction of the second, which probably means that the `%%` are preventing the sleep from executing.

Any idea what more I can do to troubleshoot this?

**Comment by magnouvean** [comment]
If you are on the latest release I have added escaping by default from #106. If you are on that release you can use only one % and see if that works. If not I don't really know what's going on.

**Comment by TimekillerTK** [comment]
Can confirm that with latest version including https://github.com/pjones/plasma-manager/pull/106, works with only one `%`. Thank you very much for the quick patch!

I'm still having the same problem with one (or two) `%`, so it's probably something else causing the problem.

I'll investigate a bit more on my end by deploying to a VM, I'll report back here if I find a solution.
