### ISSUE TITLE
services/<program>."_launch" not working

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [nix-community/plasma-manager#108]
I want to open the Warp app with Ctrl + Alt + T. This is what `nix run github:pjones/plasma-manager` shows:
In `configFile`:
```nix
"services/dev.warp.Warp.desktop"."_launch" = "Ctrl+Alt+T";
```
and I get this error: `error: A definition for option `programs.plasma.configFile."services/dev.warp.Warp.desktop"._launch' is not of type `attribute set of (submodule)'.`

**Comment by magnouvean** [comment]
The problem should be able to be solved by adding .value after the "_launch”, but I would think `rc2nix` took that into account. I'll look into it.

**Comment by magnouvean** [comment]
Do you have an idea of which file this config was read from. I can't really reproduce as all the configurations `rc2nix` generates on my system looks fine

**Comment by ChocolateLoverRaj** [comment]
This is in `.config/kglobalshortcutsrc` (there's more config above and below this text):
```
[services][dev.warp.Warp.desktop]
_launch=Ctrl+Alt+T

[services][org.kde.konsole.desktop]
_launch=none
```

**Comment by Titaniumtown** [comment]
Thank you for making this issue. I've been trying to debug this on my end. I've done something similar with alacritty and have been unable to successfully do so.

I've also tried
```
  hotkeys.commands."alacritty" = {
    name = "Launch Allacritty";
    key = "Ctrl+Alt+T";
    command = "alacritty";
  };
  ```
  to no avail. I'm on plasma 6.

**Comment by magnouvean** [comment]
In configfile on my end I don't get the "services/dev.warp.Warp.desktop"."_launch" in configFile but in the shortcuts and when placing it in the shortcuts everything works from what I can see. I don't really know what's going on here.

**Comment by ChocolateLoverRaj** [comment]
> In configfile on my end I don't get the "services/dev.warp.Warp.desktop"."_launch" in configFile but in the shortcuts and when placing it in the shortcuts everything works from what I can see. I don't really know what's going on here.

I looked at it again and for me it shows it in shortcuts too. I read it wrong before.

**Comment by ChocolateLoverRaj** [comment]
Solution for anyone else who happens to come across this issue:
```nix
programs.plasma = {
    enable = true;
    shortcuts = {
      "services/dev.warp.Warp.desktop"."_launch" = "Ctrl+Alt+T";
      "services/org.kde.konsole.desktop"."_launch" = [ ];
    };
  };
```

**Comment by Titaniumtown** [comment]
I still can't get this to work with Alacritty. I have:
```nix
  shortcuts = {
    "services/org.kde.konsole.desktop"."_launch" = [];
    "services/Alacritty.desktop"."New" = "Ctrl+Alt+T";
    "services/Alacritty.desktop"."_launch" = "Ctrl+Alt+T";
  };
  ```
(I put both "New" and "_launch" and tried just either or, same result)
  
 Inside of `.config/kglobalshortcutsrc` it results in:
```
[services][Alacritty.desktop]
New=
_launch=

[services][org.kde.konsole.desktop]
_launch=
```

I've deleted all kde/plasma configs and regenerated from home manager, I can't get this to work!!

**Comment by ChocolateLoverRaj** [comment]
@Titaniumtown make a new issue. My issue was about an error when running home manager switch

**Comment by Titaniumtown** [comment]
This is when running home manager switch

**Comment by ChocolateLoverRaj** [comment]
Do you get an error like `error: A definition for option`?

**Comment by Titaniumtown** [comment]
Making another issue
