### ISSUE TITLE
KWin Windowrules

### ISSUE THREAD

**Issue by RaHoni** [nix-community/plasma-manager#112]
Hi

would it be in scope to implement a highlevel module for kwinrulesrc?

So that you can more easily generate those.

**Comment by magnouvean** [comment]
Thanks for the suggestion. I think implementing a module for this makes sense. I'll probably do it when I get some more time (the reason I haven't implemented it already is because I don't really use them personally)

**Comment by RaHoni** [comment]
> Thanks for the suggestion. I think implementing a module for this makes sense. I'll probably do it when I get some more time (the reason I haven't implemented it already is because I don't really use them personally)

Then I will try to implement them my self an make an PR. This will probably take a bit of time.

**Comment by ada4a** [comment]
I think #199 closes this?

**Comment by magnouvean** [comment]
Yeah you are right @ugur-a. I'll close now as it's implemented.
