### ISSUE TITLE
programs.konsole.defaultProfile not working as expected

### ISSUE THREAD

**Issue by arvigeus** [nix-community/plasma-manager#113]
```nix
  programs.konsole = {
    enable = true;

    defaultProfile = "default";
    profiles.default = {
      name = "default";
      font = {
        name = "FiraCode Nerd Font Mono";
      };
    };
  };
```

Expectations: Set default profile to "default".  
Reality: I have to set `programs.konsole.defaultProfile = "default.profile"` instead to make it work.

**Comment by magnouvean** [comment]
You're right I didn't even think about that. I agree we shouldn't have to add .profile to `defaultProfile` manually. I'll fix this soon :)
