### ISSUE TITLE
error when trying to download plasma-manager

### ISSUE THREAD

**Issue by jesperstald** [nix-community/plasma-manager#132]
Hi, when trying to install plasma-manager as a module (following https://github.com/pjones/plasma-manager/tree/trunk/examples/homeManager), i get the following error:

error: unable to download 'https://github.com/pjone/plasma-manager/archive/trunk.tar.gz': HTTP error 404

**Comment by Asqiir** [comment]
There seems to be a typo. It should be `pjones`, not `pjone`.

**Comment by jesperstald** [comment]
Thanks, that is for sure the issue !! Could you correct the typo perhaps ?

**Comment by Asqiir** [comment]
Afaict the only error is happening when adding the channel (do you use channels?)

Adding the channel with the fixed URL should fix your issue

@nat-418 I think this was your commit?

**Comment by magnouvean** [comment]
I can fix it today

**Comment by magnouvean** [comment]
Should be fixed now. Thanks for reporting, stuff like this is often hard to spot.
