### ISSUE TITLE
How to set default browser?

### ISSUE THREAD

**Issue by ghost** [nix-community/plasma-manager#145]
How do I set the default browser in KDE using plasma-manager?

**Comment by magnouvean** [comment]
I would think `plasma` uses xdg-mime for this, which for example can be configured with `xdg.mimeApps` in `home-manager`.

**Comment by magnouvean** [comment]
I'm closing this, but if anyone thinks plasma-manager needs something to allow for this which isn't in `xdg.mimeApps` feel free to come up with suggestions here anyhow.
