### ISSUE TITLE
Panel configuration is being ignored

### ISSUE THREAD

**Issue by valeth** [nix-community/plasma-manager#147]
I have a simple panel configuration of one panel on top with a clock and tray icons.

With the latest home rebuild locked at ffeef9dc96a5a0e442479c94a6000f93b69aeaac, it always adds only the default panel.

Other things like background image are changed as expected.

Rolling back my home manager configuration locked at 5af3d8f504d1d63aef73eda65c7a946c3fe3ac7a does not have this problem.

**Comment by ccatterina** [comment]
Same for me, I thought i was making some mistakes in the configuration, but after seeing this issue, I tried to rollback to https://github.com/pjones/plasma-manager/commit/5af3d8f504d1d63aef73eda65c7a946c3fe3ac7a and it starts to work as expected.

**Comment by lgoette** [comment]
I got the same Problem. Thought, i did something wrong.

**Comment by magnouvean** [comment]
My bad, there is a syntax-error in one of the scripts when not using multi-displays it appears, which I just forgot to check. Should be an easy fix luckily. I will fix later today.

**Comment by valeth** [comment]
That would be weird, because I am using multiple displays.

**Comment by magnouvean** [comment]
With panels on multiple screens configured through `plasma-manager` @valeth?

**Comment by valeth** [comment]
Only one panel on the primary screen

**Comment by magnouvean** [comment]
Yeah that makes sense. I did fix the bug I was talking about in #150. Could anyone check if this solves the issues with panels? It now works on my config anyway.

**Comment by valeth** [comment]
Just tested it, seems to work like intended now
