### ISSUE TITLE
wallpaper from package not working

### ISSUE THREAD

**Issue by lgoette** [nix-community/plasma-manager#149]
When I set a wallpaper in the `workspace` option with `wallpaper = "${pkgs.libsForQt5.plasma-workspace-wallpapers}/share/wallpapers/Mountain/contents/images/5120x2880.png"`,
it is not changing.
When I enter a local path,  without referencing a package, it works.

The Path exists like that. When I use a nix shell with `nix-shell -p libsForQt5.plasma-workspace-wallpapers`, i can see the file at `/nix/store/l78xjbn4462w672q9x1k23mny6kqgx4w-plasma-workspace-wallpapers-6.0.4/share/wallpapers/Mountain/contents/images/5120x2880.png` in the nix-store.

**Comment by magnouvean** [comment]
What is the content of `~/.local/share/plasma-manager/scripts/3_set_wallpaper.sh`?

**Comment by lgoette** [comment]
I just solved the Issue. Thanks for leading me into the right direction, it was my fault that it was not working.
There are two versions packaged in nix packages:
```
- libsForQt5.plasma-workspace-wallpapers (version 5.27.11)
- kdePackages.plasma-workspace-wallpapers (version 6.0.4)
```

For some reason the Wallpaper I want to use is not included in the `libsForQt5` package but in the `kdePackages` package.
`libsForQt5.plasma-workspace-wallpapers` seems to be outdated.
