### ISSUE TITLE
Font setting on Plasma 5 is broken

### ISSUE THREAD

**Issue by luna-1024** [nix-community/plasma-manager#168]
I am running Plasma 5 on NixOS 23.11. When I try to set the global monospace font with plasma-manager it does not work, and I get a errors logged when opening the fonts section in system-settings. I suspect the issue here may be applicable to all font settings.

This looks to be due to the fact font changes in Plasma 5/6 (Qt 5 vs 6) are not accounted for. In 6, there are 6 new font fields, and Plasma 5 does not like them existing in a font configuration string. Additionally the font weight enum is changed for Plasma 6. The enum values are completely different. See: [Qt5](https://doc.qt.io/qt-5/qfont.html) vs [Qt6](https://doc.qt.io/qt-6/qfont.html) docs.

I have not ready for PR (no cleanup of dead code) working fix in [my fork](https://github.com/luna-1024/plasma-manager/compare/9239c27..4235eba). Since all the new font options are at the end of the string, I just removed the last 6 items.

**Comment by magnouvean** [comment]
This should probably go to the `plasma-5` branch, but I have had some difficulty maintaining it. The font setting was only really implemented taking `plasma 6` into account so it's not really that surprising that it doesn't work on `plasma 5`.

**Comment by ChocolateLoverRaj** [comment]
@luna-1024  Now that NixOS `24.05` is available with Plasma 6 are you considering to just upgrade to Plasma 6?

**Comment by luna-1024** [comment]
Yes, I upgraded to Plasma 6 immediately after the `24.05` release.

Since I already did the research on this bug, I have opened PR #200. Though it does seem like the maintainability of the Plasma 5 support is in question. I plan to not use it going forward as I have upgraded.
