### ISSUE TITLE
cannot set `programs.plasma.colorTheme` while `overrideConfig=false` anymore

### ISSUE THREAD

**Issue by Asqiir** [nix-community/plasma-manager#177]
When updating recently, I got the following error:
```
Exception: Plasma-manager: Persistency enabled for key "ColorScheme" in group "General" in configfile "/home/me/.config/kdeglobals" when overrideConfig is disabled. Persistency without using overrideConfig is not supported
```

This is caused by
* `overrideConfig` not being actively set (thus, defaulting to `false`)
* and `programs.plasma.theme`/`programs.plasma.colorTheme` being set (to `"breeze-dark"`/`"BreezeDark"`)

I exptect the following behaviour (by default):
* these settings being set on activation (I'd prefer immutable/non-persistent, but I do not really care)

I believe I found unintentional behaviour:
* it breaks existing configs
* one should still be able to set global themes without using overrideConfig

**Comment by BBFifield** [comment]
i have the same issue.

**Comment by tob1asr** [comment]
Looks like this was caused by #174 so it might be intentional, but with unintended side effects? A quick workaround is to just revert the new defaults in your own config:
```nix
programs.plasma.configFile.kcminputrc.Mouse.cursorTheme.persistent = false;
programs.plasma.configFile.kdeglobals.General.ColorScheme.persistent = false;
programs.plasma.configFile.kdeglobals.General.ColorSchemeHash.persistent = false;
programs.plasma.configFile.kdeglobals.Icons.Theme.persistent = false;
programs.plasma.configFile.kdeglobals.KDE.LookAndFeelPackage.persistent = false;
programs.plasma.configFile.plasmarc.Theme.name.persistent = false;
```
But it would be good to hear from one of the maintainers if that re-introduces other problems.

**Comment by pluiedev** [comment]
Same issue but with `kcminputrc.Mouse.cursorTheme`
```console
May 28 14:05:10 fettuccine hm-activate-leah[111448]:     config = KConfManager(filepath, c, override_config)
May 28 14:05:10 fettuccine hm-activate-leah[111448]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 28 14:05:10 fettuccine hm-activate-leah[111448]:   File "/nix/store/hs7xcf977s8c5qz6kswif6blbs658k0d-write_config.py", line 146, in __init__
May 28 14:05:10 fettuccine hm-activate-leah[111448]:     self._json_value_checks()
May 28 14:05:10 fettuccine hm-activate-leah[111448]:   File "/nix/store/hs7xcf977s8c5qz6kswif6blbs658k0d-write_config.py", line 178, in _json_value_checks
May 28 14:05:10 fettuccine hm-activate-leah[111448]:     raise Exception(
May 28 14:05:10 fettuccine hm-activate-leah[111448]: Exception: Plasma-manager: Persistency enabled for key "cursorTheme" in group "Mouse" in configfile "/home/leah/.config/kcminputrc" when overrideConfig is disabled. Persistency without using overrideConfig is not supported
May 28 14:05:10 fettuccine systemd[1]: home-manager-leah.service: Main process exited, code=exited, status=1/FAILURE
May 28 14:05:10 fettuccine systemd[1]: home-manager-leah.service: Failed with result 'exit-code'.
May 28 14:05:10 fettuccine systemd[1]: Failed to start Home Manager environment for leah.
warning: error(s) occurred while switching to the new configuration
```

**Comment by magnouvean** [comment]
I didn't forgot that `persistency` required `overrideConfig` to be enabled. I can fix very soon.

**Comment by magnouvean** [comment]
Hopefully this is fixed now (but do reopen if it still is a problem somehow). The issue was that I recently made some things persistent by default when using `overrideConfig` to make themes and `overrideConfig` a smoother experience (for example the cursor theme now will be the one specified in the `workspace` module from the very start), but I forgot that I had made `persistency` and `overrideConfig` incompatible on purpose, and since I just use `overrideConfig` I didn't manage to catch that bug. I will probably add some more tests in the future utilizing the `workspace` module both with and without `overrideConfig` to make these kinds of bugs be detected before merging into the codebase causing breaking changes :)
