### ISSUE TITLE
`overrideConfigExclude` not working as expected

### ISSUE THREAD

**Issue by InternetUnexplorer** [nix-community/plasma-manager#184]
I've been using this configuration for a while now, so that my `kcminputrc` is not reset:
```nix
programs.plasma = {
  enable = true;
  overrideConfig = true;
  overrideConfigExclude = [ "kcminputrc" ];
};
```
This worked previously, but this recent change causes `programs.plasma.configFile.kcminputrc` to exist:
https://github.com/pjones/plasma-manager/blob/7c816ab287574c317ac586900718aa7ab85f2f17/modules/workspace.nix#L181

This seems to cause `write_config.py` to overwrite `kcminputrc` with nothing, erasing the settings there.

Because this file often contains convoluted hardware-specific names (e.g. `[Libinput][1267][13016][ASUE120C:00 04F3:32D8 Touchpad]`), manually enabling persistence for specific keys is difficult. 

Is there a way to ensure that this file is not erased when using `overrideConfig`?

**Comment by magnouvean** [comment]
This seems to be a bug regarding the persistence options not respecting the `overrideConfigExclude` option. I can take a look at it when I get some more time for the project (in a couple weeks).

**Comment by InternetUnexplorer** [comment]
Thanks for the reply! This seems pretty straightforward so I'm going to try to fix it myself if possible, I think it just comes down to which solution people prefer.
