### ISSUE TITLE
Update breaks panel and walllpaper settings.

### ISSUE THREAD

**Issue by YaroKasear** [nix-community/plasma-manager#188]
I just updated my flake and I noticed that plasma-manager no longer installs the scripts to update the panel or wallpapers. As a result, it no longer applies the settings in my Flake that change the wallpaper and panel. 

Is this a deliberate change? If so, what's the correct way to configure the panel and wallpaper now, as the way documented in the examples doesn't work for me anymore.

**Comment by magnouvean** [comment]
This isn't deliberate. There was a recent change which merged the panel and wallpaper application into one script. Could you share the config. It works fine on my end, but I may have missed some edge case.

**Comment by YaroKasear** [comment]
Sure thing. I made a branch of my Flake. Feel free to look.

https://github.com/YaroKasear/flakes/tree/plasma-update

Specifically, files important to Plasma are:

https://github.com/YaroKasear/flakes/blob/plasma-update/modules/nixos/plasma/default.nix <-- This is for sddm, mostly. No issue here and doesn't use plasma-manager.

https://github.com/YaroKasear/flakes/blob/plasma-update/modules/home/gui/plasma/default.nix <-- This is my home-manager module for Plasma, and where the defaults are set.  I have workspace.wallpaper defaulting to a setting in the user module, but it is no longer working as of latest plasma-manager update.

https://github.com/YaroKasear/flakes/blob/plasma-update/homes/x86_64-linux/yaro%40loki/default.nix <-- My standard user, does some overriding and customization of the panel.

**Comment by magnouvean** [comment]
I don't really see anything wrong there. Are the files at
`~/.local/share/plasma-manager/scripts/2_desktop_script_panels_and_wallpaper.sh`
and
`~/.local/share/plasma-manager/data/desktop_script_panels_and_wallpaper.js`
not generated?

**Comment by YaroKasear** [comment]
~/.local/share/plasma-manager is empty. 

A comparison between a profile with latest plasma-manager and one on the last known good pinned below. It shows that pretty much all the plasma manager scripts get removed (Along with another user's wallpaper.):

```console
<<< /nix/var/nix/profiles/system-1098-link
>>> /nix/var/nix/profiles/system-1099-link
Removed packages:
[R.]  #1  bri.png                                                  <none>
[R.]  #2  hm_autostartplasmamanagerautostart.desktop               <none> x2
[R.]  #3  hm_plasmamanagerdatadesktop_script_apply_panels.js       <none> x2
[R.]  #4  hm_plasmamanagerrun_all.sh                               <none> x2
[R.]  #5  hm_plasmamanagerscripts2_desktop_script_apply_panels.sh  <none> x2
[R.]  #6  hm_plasmamanagerscripts3_set_wallpaper.sh                <none> x2
Closure size: 3006 -> 2995 (25 paths added, 36 paths removed, delta -11, disk usage -47.7KiB).
```

**Comment by magnouvean** [comment]
That's weird, I'm having trouble trying to reproduce this. Have you tried to change some value in the panel and try to regenerate the config. Are you also on the very last version? The script should be created when [any kind of wallpaper is set or a panel is present](https://github.com/pjones/plasma-manager/blob/aaaeedd10e5be98cd08275197660300820553d12/modules/workspace.nix#L195)

**Comment by YaroKasear** [comment]
Do you mean for me to make a change in Plasma's settings manager or in my Flake?

**Comment by magnouvean** [comment]
In one of the panels in the plasma-manager config for example

**Comment by YaroKasear** [comment]
No, it still just removes the scripts entirely.

**Comment by magnouvean** [comment]
I may have found the problem. If you set `workspace.colorScheme = "BreezeDark"` I'm assuming the scripts are generated.

**Comment by YaroKasear** [comment]
Indeed, this seems to have restored the scripts. I've not yet tested if they run, but I assume they do.

**Comment by magnouvean** [comment]
Yeah I'm pretty sure that's the problem. I'll look into if I can fix this immediately.

**Comment by YaroKasear** [comment]
Thanks for the help.

**Comment by magnouvean** [comment]
Would be great if you could test with flake url `github:magnouvean/plasma-manager/bugfix-script-disappearing` to verify that the pr linked fixes the issue. If this works I'll merge right away. From my little testing it seems to do the trick.

**Comment by YaroKasear** [comment]
Hmmm, commenting out the colorscheme and using your fork seems to show the scripts being removed again.

**Comment by magnouvean** [comment]
Hmm, I'm a little stuck on this. It might take a little bit of time before I can resolve this. I'll notify again when I seemingly get it working. Until then you can at the very least use the old commit.

**Comment by YaroKasear** [comment]
I'll just set the colorscheme for now and keep my eye on this issue. Let me know if you need anything more from me.

**Comment by magnouvean** [comment]
Thanks. I think I may have figured it out now. Does the latest version now work?

**Comment by YaroKasear** [comment]
Looks like that worked. The only script not appearing is applythemes, but that's because I commented out the colorscheme to test your fix.

**Comment by magnouvean** [comment]
Great. The applythemes script indeed shouldn't appear unless any themes are set so that's all good. I'll merge right away. Thanks for notifying me about this and doing the testing, it's pretty hard to test all sorts of different combinations of configurations :)
