### ISSUE TITLE
Feature request: Energy settings

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [nix-community/plasma-manager#194]
I like to always change the power button action from "Show logout screen" to "Sleep". It would be nice to be able to configure that in NixOS config.

**Comment by magnouvean** [comment]
Just in case it wasn't clear from the PR, this (and some other things) is now supported and can be enabled through the `programs.plasma.powerdevil.powerButtonAction` option. Setting it to `sleep` should achieve the use-case mentioned above. For a full list of supported values as per plasma 6.1.3 see the `powerButtonActions` attrset found [here](https://github.com/nix-community/plasma-manager/blob/b967e042896de0f64513d4596e3d1f3eae445d1c/modules/powerdevil.nix#L5)
