### ISSUE TITLE
System Monitor add more options.

### ISSUE THREAD

**Issue by jaanonim** [nix-community/plasma-manager#196]
I'm missing `showTitle` and `showLegend` options, it would be nice to have them in systemMonitor wiget. 
It would be added to https://github.com/pjones/plasma-manager/blob/trunk/modules/widgets/system-monitor.nix file.

**Comment by magnouvean** [comment]
Sure, I'll add these soon.

**Comment by magnouvean** [comment]
OK so `showTitle` should at the very least be available now. I tried to add `showLegend` in the exact same way but did not have any luck here. I managed to write the correct key, but for some reason this did not cause the setting to be applied until `plasmashell` was restarted, which hinders its use with `plasma-manager`. This is a `plasma` problem of some sort, and there are other parts where we have had the same problem before (multi-monitor panels and desktop-modes for example). Unless we can find some solution around this `showLegend` will have to wait.
