### ISSUE TITLE
Is ~/.config/powermanagementprofilesrc skipped intentionally

### ISSUE THREAD

**Issue by haizaar** [nix-community/plasma-manager#20]
Hi there,

Thanks again for writing this module. I'm now crafting my KDE configuration and nocited that `run2nix` doesn't include `powermanagementprofilesrc` (the one that controls power settings). Is this intentional?

**Comment by pjones** [comment]
Yes, it's intentional.  My reasoning is that this file is going to be very specific to the current machine.

The `rc2nix` tool really needs a command line option to include files that it doesn't include by default.  In that case, this issue is related to #12.

**Comment by haizaar** [comment]
Got'ya. You mean something beyond `-a` (i.e. a default list) ?

**Comment by pjones** [comment]
Oh boy, I completely forgot about `-a`.  Yes, that would be a way to get `rc2nix` to pick up the file you want to translate to Nix.

**Comment by haizaar** [comment]
Thanks again for your support.
