### ISSUE TITLE
Systray module fails with "error: cannot coerce null to a string."

### ISSUE THREAD

**Issue by YaroKasear** [nix-community/plasma-manager#205]
Something with the latest update seems to have run afoul with my configuration. At first it didn't even look like it involved plasma-manager until I ran `nix flake check --show-trace.`

Commenting out the use of the system tray module eliminates this issue, but I'm not sure exactly what changed that is causing this error.

I have attached the trace. I may need to work around this by configuring the system tray without the use of the module. 

[trace.txt](https://github.com/user-attachments/files/15821948/trace.txt)

**Comment by magnouvean** [comment]
I did notice. We forgot to check something in a recent PR. This should after #206 is merged though :)

**Comment by YaroKasear** [comment]
The PR fixed the issue.
