### ISSUE TITLE
Digital clock panel widget does not show week numbers in calendar

### ISSUE THREAD

**Issue by oynqr** [nix-community/plasma-manager#207]
I have the following widget in my main panel:
```nix
{
  digitalClock = {
    calendar.showWeekNumbers = true;
  };
}
```
However, when I open the calendar, the week numbers are not actually shown. In the digital clock settings, "Show week numbers" shows as disabled:
![Screenshot_20240613_164237](https://github.com/pjones/plasma-manager/assets/71629732/e6537d77-d078-458a-beba-9ba24be1e23d)

Enabling this setting causes week numbers to show up until the next login, at which point the setting reverts.

I do not use `overrideConfig`.

**Comment by magnouvean** [comment]
It seems like the option exists, but we forgot to include the correct configuration in the PR for the digital clock widget. I'll see if I can fix

**Comment by magnouvean** [comment]
If you set the plasma-manager url to `github:magnouvean/plasma-manager/digitalclock-weeknumbers` I assume this works?

**Comment by oynqr** [comment]
That branch does fix it. Thanks!
