### ISSUE TITLE
How to Handle Themes

### ISSUE THREAD

**Issue by TheMoxyFoxy** [nix-community/plasma-manager#212]
Hello everyone :))

I'm trying to use plasma-manager for the first time. I really wish to use the Moe theme, but I am having some difficulty getting it into `~/.local/share/plasma`. I'm trying to download the theme via (ignore the `programs.plasma` being incomplete I plan to do it after I can actually *copy* the theme):
```nix
{ pkgs, ... }:

let
  theme = pkgs.fetchgit {
    url = "https://gitlab.com/jomada/moe-theme";
    rev = "39215b6305af3ecec67d8c6dd2c2721f60c23594";
    hash = "sha256-zMahxlpEcX7t2EWs0jyMAzEpuYoQ5mj02jmK6wFbrW4=";
  };
in
{
  home.file.".local/share/plasma/moe".source = "${theme}/Moe";

  programs.plasma = {
    workspace = {
      clickItemTo = "open";
    };
  };
}
```
However, I get the error `ln: failed to create symbolic link '/home/eve/.local/share/plasma/moe': Read-only file system`. This is because the `~/.local/share/plasma` directory is actually the nix store `/nix/store/...-home-manager-files/.local/share/plasma`. Is there any way to have plasma-manager ingest this theme directory or get it straight from the KDE Store? And what about anything else I wish to download from an outside source, such as a cute cursor theme?

**Comment by magnouvean** [comment]
I think the best way would be to create a nix-package for this and install this using either home-manager or as a system package. For example the following may work:
```nix
  moe-theme = pkgs.stdenv.mkDerivation {
    pname = "moe-theme";
    version = "latest";
    src = pkgs.fetchgit {
      url = "https://gitlab.com/jomada/moe-theme";
      rev = "39215b6305af3ecec67d8c6dd2c2721f60c23594";
      hash = "sha256-a6L8xSzW8yMXTfcZF08Gv3b0Q/Leb+/D3ln/ISHmLbk=";
    };
    installPhase = ''
      mkdir -p $out/share/plasma
      cp -aR * $out/share/plasma
    '';
  };
```
And then put `moe-theme` in you `home.packages` or `environment.systemPackages`.

In other words plasma-manager doesn't really handle theme-installation at all, but does allow you to apply installed themes, cursors, icons etc.. Installation of these themes can be done using either packages in `ǹixpkgs` or making your own derivations (as in the example above). If you manage to make the package you could also make a PR in the `nixpkgs` repo to get them into `nixpkgs`. Maybe in the future we could add something like kde store support, but that probably won't happen too soon as I seem to remember it needing to interact with it's own API.

**Comment by TheMoxyFoxy** [comment]
Wouldn't that keep the data in the nix store? How would I copy the files over to `.local/share/plasma` where plasma expects them to be? I tried a few approaches with the derivation but couldn't get it to work. No matter what I do, there's permission issues.

**Comment by TheMoxyFoxy** [comment]
Should specify that I'm doing this via home-manager, and maybe that's causing problems

**Comment by magnouvean** [comment]
You shouldn't need to link it to `.local/share/plasma` to use the theme if you are installing the package as above (it didn't seem like it from my testing at the very least).

**Comment by pluiedev** [comment]
> Wouldn't that keep the data in the nix store? How would I copy the files over to `.local/share/plasma` where plasma expects them to be? I tried a few approaches with the derivation but couldn't get it to work. No matter what I do, there's permission issues.

If you want it to be at *specifically* `~/.local/share/plasma` you can link to it via [`xdg.dataFile`](https://nix-community.github.io/home-manager/options.xhtml#opt-xdg.dataFile), but due to the magic known as [`environment.pathsToLink`](https://search.nixos.org/options?channel=unstable&show=environment.pathsToLink&from=0&size=50&sort=relevance&type=packages&query=pathsToLink), if you just install the package like @magnouvean has shown, it will be automagically detected by Plasma.
