### ISSUE TITLE
Khotkeysrc attributes defined multiple times

### ISSUE THREAD

**Issue by ada4a** [nix-community/plasma-manager#215]
When I run `rc2nix` and then try to build the system, I get the following error:
```
error: attribute 'khotkeysrc.Icons."Themex5b$dx5d"' already defined at <nix_store_path>

at /nix/store/6rkg088qs6ppxrzg1dzjbxzds2i8h69z-source/user/plasma/rc2nix-ed.nix:808:7:
           807|       "khotkeysrc"."Icons"."Theme\x5b$d\x5d" = "";
           808|       "khotkeysrc"."Icons"."Themex5b$dx5d" = "";
                  |       ^
           809|       "khotkeysrc"."KDE"."SingleClick" = "";
```
The reason can already be seen in the stack trace: the attribute names are duplicated - once with brackets (`\x5b` = `[`) escaped, and once without.

There's something else which may or may not be an error: the attribute names are actually written **three** times - in addition to the two versions with brackets shown above, they're also written once without any brackets at all. Here's what that looks like:
``` nix
{
    # snip
    "khotkeysrc"."DirSelect Dialog"."DirSelectDialog Size" = "";
    "khotkeysrc"."DirSelect Dialog"."DirSelectDialog Size\x5b$d\x5d" = "";
    "khotkeysrc"."DirSelect Dialog"."DirSelectDialog Sizex5b$dx5d" = "";
    "khotkeysrc"."General"."AllowKDEAppsToRememberWindowPositions" = "";
    "khotkeysrc"."General"."AllowKDEAppsToRememberWindowPositions\x5b$d\x5d" = "";
    "khotkeysrc"."General"."AllowKDEAppsToRememberWindowPositionsx5b$dx5d" = "";
    # snip
}
```
These are just examples - in reality this happens for all the attributes under `khotkeysrc`

**Comment by ada4a** [comment]
Oh, so I see that these options are actually defined in `khotkeyrc` itself (not a symlink to Nix Store or something, just a plain file in `.config`), e.g., for `DirSelect Dialog`:
``` kconfig
[DirSelect Dialog]
DirSelectDialog Size=
DirSelectDialog Size\x5b$d\x5d=
DirSelectDialog Sizex5b$dx5d=
```
... which would mean that `rc2nix` does what it's supposed to. But then the question is, should these entries have been in `kconfigrc` in the first place?

**Comment by magnouvean** [comment]
I'm not sure what you refer to as `kconfigrc` (it doesn't exist on my system at least), but it should maybe not be included by `rc2nix`. It should be easy enough to blacklist it from being included in the `nix` output code if you think that makes sense (I agree it doesn't really belong there) as we already have functionality for that. With that said `rc2nix` hasn't really been a focus much since we introduced `overrideConfig`, so it should be more viewed as something to get started with than a tool which generates the perfect configuration.

**Comment by ada4a** [comment]
Oh, sorry, that was supposed to be `khotkeysrc`, the file I was talking about in the rest of the message.

Good to know about the `overrideConfig` stuff, thanks! It seems like I was kind of abusing the system by just regularly running `rc2nix` and taking its output straight into my config. I'll make sure to make a more intelligent use of the options in the future.

Thanks again!
