### ISSUE TITLE
Unicode not working correctly for configFile

### ISSUE THREAD

**Issue by techtino** [nix-community/plasma-manager#22]
I'm trying to set my panel to floating, this requires the following in ~/.config/plasmashellrc:

```
[PlasmaViews][Panel 2]
floating=1
```

However I don't seem able to set this up, when I do:
```
configFile = {
            "plasmashellrc"."PlasmaViews][Panel 2"."floating" = 1;
          };
```

It produces the following:
```
[PlasmaViews\x5d\x5bPanel 2]
floating=1
```

So I suppose unicode isn't correctly translated to the config files.

Is there a better way of doing this that I am missing?

Thanks.

**Comment by techtino** [comment]
Ah I've just seen https://github.com/pjones/plasma-manager/issues/8, which seems to be what I want anyway.

**Comment by hatch01** [comment]
I also have a problem on char encoding.
With the config : 
```nix
shortcuts = {
      kwin = {
        "Switch to Desktop 2" = "Meta+É"; 
      };
};
```
it just does not set the shortcut because of the É (the key 2 without maj on azerty keyboard)
However, it works if I set another thing like &;

**Comment by magnouvean** [comment]
I believe this was fixed in some recent PR, so I'm closing this issue. If this is still a problem feel free to reopen.
