### ISSUE TITLE
Implement widget-specific options and installation for third-party widgets.

### ISSUE THREAD

**Issue by HeitorAugustoLN** [nix-community/plasma-manager#229]
## Objective

Create widget-specific options to facilitate the configuration and installation of third-party widgets in KDE Plasma environments. This enhancement aims to broaden user customization options within plasma-manager by making it easy to install and customize third-party widgets into the Plasma desktop environment, thereby enriching the user experience with plasma-manager.

## Things needed to do

For each widget that will be implemented, there are three things that need to be done:

1. Package the widget
2. Make it available in nixpkgs
3. Implement the widget-specific options in plasma-manager

### Widget packaging 

As of now, there is currently only one (that I know of) widget package available in nixpkgs for Plasma 6. And another one (that I know of) with a pull request open in nixpkgs. Them being:

#### In nixpkgs

- application-title-bar: nixos/nixpkgs#318103
- plasmusic-toolbar: nixos/nixpkgs#319671

> [!NOTE]
> Can have more that I don't know

#### Pull request open

> [!NOTE]
> Can have more that I don't know

#### Not packaged yet

> [!NOTE]
> Here we can add widgets asked by the users

#### Option

- Introduced in #233 

#### Supported packages:

- application-title-bar: #233

#### Done

- application-title-bar: #234 

#### Not started

**Comment by magnouvean** [comment]
I reckon this is done now and that the further discussions can be held in the pr-s for future widgets
