### ISSUE TITLE
Feature: Supports fine-grained (option-level) declarative configuration (overrideConfig)

### ISSUE THREAD

**Issue by luochen1990** [nix-community/plasma-manager#243]
Currently, overrideConfig is a global option, which means that I either enable it for all options or disable it for all options. However, there are some special options in KDE, or rather, they are not options but the state of the software, which may only apply to specific machine and not to other machines (if we use home-manager or plasma-manager, I believe in many cases we would like our configurations to be transferable between multiple different devices). Examples of such "options" include:
`"kdeglobals"."KScreen"."ScreenScaleFactors" = "HDMI-1\x3d1.5;DP-1\x3d1.5;HDMI-2\x3d1.5;DP-2\x3d1.5;HDMI-3\x3d1.5;";`，It appears that this option enumerates all display ports for the device, but when I apply these configurations on different devices, these options are definitely no longer applicable. At this point, I hope to specify these options individually as variable state, while maintaining the declarative nature of the overall configuration.

One possible implementation: Introduce a special value, such as `keepState`, where specifying `"kdeglobals"."KScreen"."ScreenScaleFactors" = "keepState"` will cause the plasma-manager to retain its previous state. This `keepState` might simply be something like `{ _special = "keepState"; }`.

**Comment by magnouvean** [comment]
I believe this is already supported. You should for example be be able to use:
```nix
"kdeglobals"."KScreen"."ScreenScaleFactors".persistent = true;
```
Is that what you're looking for?

**Comment by luochen1990** [comment]
> Is that what you're looking for?

Thank you, this looks promising,  so where can I find the related document/manual ?

**Comment by magnouvean** [comment]
There's no manual at the moment (we probably should add one), but to see the options which are supported for the `files` module take a look at [advancedSettingsType](https://github.com/nix-community/plasma-manager/blob/71c3fb6eb0767923335662aa33a06f983c2fbeae/lib/types.nix#L7). For other cases I would suggest looking at [the examples directory](https://github.com/nix-community/plasma-manager/tree/trunk/examples), but I don't think there are any examples for persistence there yet (I can add one though).
