### ISSUE TITLE
Shortcuts with multiple key combinations are set incorrectly

### ISSUE THREAD

**Issue by toast003** [nix-community/plasma-manager#25]
Making meta+ctrl+up and meta+ctrl+right switch one desktop to the right though the settings writes `Switch One Desktop to the Right=Meta+Ctrl+Up\tMeta+Ctrl+Right,Meta+Ctrl+Right,Switch One Desktop to the Right`  in .config/kglobalshortcutsrc, while doing the same thing with plasma manager with 
```
shortcuts = {
	"kwin" = {
		"Switch One Desktop to the Left" = [ "Meta+Ctrl+Left" ];
		"Switch One Desktop to the Right" = [ "Meta+Ctrl+Right" "Meta+Ctrl+Up"];
	};
};
```
writes `Switch One Desktop to the Right=Meta+Ctrl+Right\tMeta+Ctrl+Up,,`, which doesn't work

**Comment by manuelbb-upb** [comment]
I have this issue still with 
```
shortcuts = {
  "services/org.kde.krunner.desktop"."_launch" = ["Meta+U" "Alt+F2"];
};
```
giving 
```
[services][org.kde.krunner.desktop]
_launch=\tMeta+U\tAlt+F2
```

**Comment by HeitorAugustoLN** [comment]
> I have this issue still with
> 
> ```
> shortcuts = {
>   "services/org.kde.krunner.desktop"."_launch" = ["Meta+U" "Alt+F2"];
> };
> ```
> 
> giving
> 
> ```
> [services][org.kde.krunner.desktop]
> _launch=\tMeta+U\tAlt+F2
> ```

I will fix this later when I get home
The issue is here:
https://github.com/nix-community/plasma-manager/blob/508a077405fa700de0248e7f84bc4fefbd308dd9/modules/shortcuts.nix#L33

**Comment by HeitorAugustoLN** [comment]
@manuelbb-upb fixed :)

**Comment by magnouvean** [comment]
While this might work fine with the latest kde plasma, I'm pretty sure I wrote it this way because it fixed some kind of problem at the time. We'll quickly figure out if things work as they should on the latest version though :)
