### ISSUE TITLE
kscreenlocker.wallpaper is not working, but workspace.wallpaper works with the same value

### ISSUE THREAD

**Issue by HeitorAugustoLN** [nix-community/plasma-manager#254]
Error:
![image](https://github.com/nix-community/plasma-manager/assets/44377258/bc464f4d-d122-4e28-bc96-889b164324c0)

I'm using the same wallpaper for both screenlocker and the workspace, but only kscreenlocker gets an error.

This is how i'm setting up my wallpapers. `wallpapers` is an input from `github:HeitorAugustoLN/wallpapers` which is my flake for wallpapers, that gets me my wallpapers and then exports into variables, so I can use it like this:

```nix
kscreenlocker.wallpaper = wallpapers.abstract.catppuccin.topography;

workspace.wallpaper = wallpapers.abstract.catppuccin.topography;
```

**Comment by HeitorAugustoLN** [comment]
It works after changing it to:

```nix
kscreenlocker.wallpaper = builtins.toString wallpapers.abstract.catppuccin.topography;
```

Apparently if it is a string it works, but i don't know if it should be like this

**Comment by magnouvean** [comment]
Yeah it shouldn't be like this. I'm on it (though currently my config doesn't build due to some other non plasma-manager related problem so it might take a few days).
