### ISSUE TITLE
Application-title-bar, plasmusic undefined wuth Auto installing

### ISSUE THREAD

**Issue by mglants** [nix-community/plasma-manager#259]
Fail as it tries, to add to extraWidgets
`error:
       … while calling the 'head' builtin

         at /nix/store/2k0r4pk0hzjzk9iwyi61xc0z4qv791j9-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/2k0r4pk0hzjzk9iwyi61xc0z4qv791j9-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: undefined variable 'application-title-bar'

       at /nix/store/ammilqx53b1sqaa83xhs9812iw129vmr-source/modules/panels.nix:149:135:

          148|     home.packages = with pkgs; []
          149|       ++ lib.optionals (lib.elem "application-title-bar" cfg.extraWidgets || hasWidget "com.github.antroids.application-title-bar") [ application-title-bar ]
             |                                                                                                                                       ^
          150|       ++ lib.optionals (lib.elem "plasmusic-toolbar" cfg.extraWidgets || hasWidget "plasmusic-toolbar") [ plasmusic-toolbar ];
task: Failed to run task "nix:apply-nixos": exit status 1`

**Comment by magnouvean** [comment]
Which `nixpkgs` version are you running. If it is stable this is probably due to `plasmusic-toolbar` and `application-title-bar` not being available there yet.

**Comment by HeitorAugustoLN** [comment]
It is probably due to these packages being available currently only in nixos-unstable. But if you want to use it, you can add them as custom packages in your nixos configuration or get them from nixos-unstable using an overlay. I can help you with that if you need.

**Comment by mglants** [comment]
I can access unstable packages with pkgs.unstable, but don't know how to pass it to plasma-manager

**Comment by HeitorAugustoLN** [comment]
> I can access unstable packages with pkgs.unstable, but don't know how to pass it to plasma-manager

If your flake have an nixos-unstable input, you could make the nixpkgs from plasma-manager follow it

**Comment by HeitorAugustoLN** [comment]
Like this:

```nix
inputs = {
  nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
  nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
  home-manager = {
    url = "github:nix-community/home-manager";
    inputs.nixpkgs.follows = "nixpkgs";
  };
  plasma-manager = {
    url = "github:nix-community/plasma-manager";
    inputs.nixpkgs.follows = "nixpkgs-unstable";
    inputs.home-manager.follows = "home-manager";
  };
};
```

**Comment by HeitorAugustoLN** [comment]
I didn't test, but it should work

**Comment by mglants** [comment]
thank you
