### ISSUE TITLE
kwin/NightLight/location: use `lib.types.number` instead of `lib.types.str`

### ISSUE THREAD

**Issue by ada4a** [nix-community/plasma-manager#277]
Is there any reason why `lib.types.str` is used here?
https://github.com/nix-community/plasma-manager/blob/b967e042896de0f64513d4596e3d1f3eae445d1c/modules/kwin.nix#L233-L246
The only one I can imagine is to avoid parsing the value as either an int or a float, but `lib.types.number` [handles that](https://github.com/NixOS/nixpkgs/blob/997332b0816e693d7985138f78757280245f7933/lib/types.nix#L390).

I'd make a quick PR to implement the change if no one objects.

**Comment by HeitorAugustoLN** [comment]
It could use `lib.types.number`. But it could cause syntax errors if the user doesn't know nix well.

![image](https://github.com/user-attachments/assets/6ebdff3d-6ed0-4276-b332-9f06c5e469fa)

That's why I preferred to make it a string.

**Comment by ada4a** [comment]
Assigning a float value to a variable (in our case, to the module options) seems to work just fine though
```
nix-repl> a = -4.5

nix-repl> builtins.typeOf a
"float"

nix-repl> p = {a = -6.5; b = -5.6;}

nix-repl> builtins.typeOf p.a
"float"
```

But not a big deal either way

**Comment by HeitorAugustoLN** [comment]
I will test, but I think it will not be a good change, as float values are limited in nix. I think it only gets up to 5 decimal numbers.
