### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by pjones** [nix-community/plasma-manager#28]
I no longer use Plasma and thus this project tends to get de-prioritized.  I'm hoping that someone will volunteer to maintain this project and help move it forward.

/cc @ProminentRetail @toast003 @nazarewk @17hoehbr @techtino @MatthewCash @ncfavier

**Comment by toast003** [comment]
I would like to volunteer, but I'm very new to contributing to open source and don't know nix that well so I'm not sure that I would be a good maintainer

**Comment by nazarewk** [comment]
I'm actually also considering moving away from KDE and back into Sway.
Initially I was positively surprised by the number of seamless features it has, but getting more and annoyed by those not-quite or not-always working, poor responsiveness and lack of working window tiling solution.

**Comment by pjones** [comment]
@toast003 There's no better way to learn than to dive right in!  If you have the time and willingness to learn then I'm also happy to help you as the need arises.

@nazarewk I completely agree with your assessment of KDE.  I really wanted to like it, especially the fact that it does all the things you expect from a modern desktop without having to hand pick each component.  But in the end I want my computer to bend to my will and work style, not the other way around.  Trying to make KDE work the way I think it should is an uphill battle.  I went back to a plain X session with herbsluftwm.  There's a lot more to configure, but then it just works.

**Comment by toast003** [comment]
@pjones After thinking about it for a bit (and a couple of rounds of https://nixcloud.io/tour) I think I'm ready

**Comment by pjones** [comment]
@toast003 Thank you so much!  I've sent you an invite to join the project.

I'm going to keep this issue open since we can always use more people willing to help maintain the project.

**Comment by magnouvean** [comment]
I might also be interested in helping maintaining this as I'll have some spare time in a couple months and am planning on moving to plasma then. I know a little bit of nix and plan to learn more forwards :)

**Comment by GetPsyched** [comment]
Dropping in here to say hi! Sucks that this project has very little activity. I'm gonna be switching to KDE Plasma soon and would definitely actively send in contributions :)

Thanks for the amazing initiative!

**Comment by haizaar** [comment]
I've been truly enjoying this project over the last year and much hope it will continue to get attention from all the new joiners. Thank you all for doing such a great job :pray:
