### ISSUE TITLE
Support for configuring panels

### ISSUE THREAD

**Issue by magnouvean** [nix-community/plasma-manager#29]
This is a tracker issue for planned support of configuring panels from plasma-manager. A.t.m. I don't see a way to do this, but it should be possible to do using some javascript and qdbus (I have done something similar before). I'll try to put some effort into this in about a month and see if this is a possibility. It should be possible to configure the following among other things:
* panel-height
* panel-location
* widgets and widget settings

However I do believe there is going to be some limitations on the plasma-side from what I can remember from last time I tried this out. https://develop.kde.org/docs/plasma/kwin/ should be of help here. Maybe things are a little better in plasma 6 as well hopefully when it comes to the scripting possibilities, though I have not heard anything about that.

**Comment by toast003** [comment]
Another way we could do this is by modifying the config files directly, although from my (small) time tinkering with it we would need to read `plasma-org.kde.plasma.desktop-appletsrc` and `plasmashellrc` beforehand to figure out what [containment](https://community.kde.org/Plasma/Vocabulary#Containment)  ID to write configs to

**Comment by magnouvean** [comment]
Yes that could be an idea, though I seem to remember from previous experiences that it wasn't that straightforward doing so. One clear downside of using my approach proposed above would be that as far as I remember the plasma scripting method needed kde plasma running already, so it would not work if ran from gnome or during installation, but I'll really have to see about that in the future. Reading from `desktop-appletsrc` or `plasmashellrc` could have problems that we then read from another file on the system, which is a bit un-nix-like, but we'll have to weight the benefits of it up I think.

**Comment by toast003** [comment]
> One clear downside of using my approach proposed above would be that as far as I remember the plasma scripting method needed kde plasma running already, so it would not work if ran from gnome or during installation

Instead of configuring panels on activation, we could drop a script at `.config/plasma-workspace/env` or `.config/autostart` to configure them when plasma starts.
The intended purpose of `env` is to run scripts that set environment variables, however they run earlier than regular autostart entries, so it might be useful

**Comment by magnouvean** [comment]
This is now supported through the `panels` module (implemented in pr #49. I will add some examples/documentation soon. Closing as support is now implemented.
