### ISSUE TITLE
How i can use widgets

### ISSUE THREAD

**Issue by salko-ua** [nix-community/plasma-manager#303]
In modules/widgets i have some options how can i write this
 in home-manager
 programs.plasma = {
  enable = true;
  .#    how write options to widgets
};

I will be very grateful for your help

**Comment by HeitorAugustoLN** [comment]
You need to declare widgets in your panel

For example:

```nix
programa.plasma = {
  enable = true;
  panels = [
    {
      floating = true;
      height = 44;
      widgets = [
        # You can define widgets by using a simple string of the widget ID, 
        # But that way you can't configure them
        "org.kde.plasma.kickoff"
        # You also can define them like this, that way you can configure the widgets
        # Simple string widgets are also transformed into this, but without any configuration
        {
           name = "org.kde.plasma.kickoff";
           config.General.icon = "nix-snowflake-white";
        }
        # And you can use widget-specific options for setting up widgets in a easier way
        # Widget-specific options are also converted into the last syntax I've showed you
        # You can also manually set any of these configurations with widget-specific options using the `settings` option
        {
          kickoff = {
            sortAlphabetically = true;
            settings = {
              General.icon = "nix-snowflake-white";
            };
          };
        }
      ];
    }
  ];
};
```

**Comment by salko-ua** [comment]
thx very much !

**Comment by salko-ua** [comment]
How i can set 'kickoff to " `application dashbord` or `application menu` "?
How i can setting keyboard layout `display style`

**Comment by HeitorAugustoLN** [comment]
> How i can set 'kickoff to " `application dashbord` or `application menu`"?

- Application menu: `"org.kde.plasma.kicker"`
- Application dashboard: `"org.kde.plasma.kickerdash"`

But we currently don't have any widget-specific options for them.

> How i can setting keyboard layout `display style`

Do you mean in the system tray? If it is like, here is an example of how you can define it the items are shown or not in the system tray:

```nix
programa.plasma = {
  enable = true;
  panels = [
    {
      floating = true;
      height = 44;
      widgets = [
        {
          systemTray = {
            items.shown = [
              "org.kde.plasma.keyboardlayout"
            ];
          };
        }
      ];
    }
  ];
};
```

**Comment by salko-ua** [comment]
yes, it is in the system tray, but if you go to its settings, you will see that there is '' is it possible to configure it somehow?

it is in keyboard-layout that there is a setting inside 'display style'

image: https://imgur.com/gallery/settings-nQlZHzY


and where can I find these values, such as application dashborad/menu and other widgets that you gave me? are they available somewhere in a convenient form?

**Comment by HeitorAugustoLN** [comment]
You can set it like this:
```nix
programa.plasma = {
  enable = true;
  panels = [
    {
      floating = true;
      height = 44;
      widgets = [
        {
          systemTray = {
            items.config = {
              "org.kde.plasma.keyboardlayout".config.General.displayStyle = "Flag"; 
              # values are Label (0), Flag (1) and LabelOverFlag (2) or their respective numbers
            };
          };
        }
      ];
    }
  ];
};
```

I will make a module for it, to make it more simple

**Comment by HeitorAugustoLN** [comment]
> and where can I find these values, such as application dashborad/menu and other widgets that you gave me? are they available somewhere in a convenient form?

You can check the names and the configuration values in `plasma-org.kde.plasma.desktop-appletsrc` in `~/.config`

Or you can go into the system path symlinks and `share/plasma/plasmoids` and see the available widgets

To get the current system path run `whereis sh`

**Comment by HeitorAugustoLN** [comment]
I will also create widget-specific options for kickerdash and kicker, when i have a bit of time

**Comment by salko-ua** [comment]
i find this in ~/.config/plasma-org.kde.plasma.desktop-appletsrc  


```
[Containments][240][Applets][246]
immutability=1
plugin=org.kde.plasma.keyboardlayout

[Containments][240][Applets][246][Configuration][ConfigDialog]
DialogHeight=539
DialogWidth=720

[Containments][240][Applets][246][Configuration][General]
displayStyle=Flag
```

but how i can write it in code

**Comment by HeitorAugustoLN** [comment]
> but how i can write it in code

https://github.com/nix-community/plasma-manager/issues/303#issuecomment-2283676814

**Comment by HeitorAugustoLN** [comment]
Created widget-specific options for **application menu**, **application dashboard** too.
