### ISSUE TITLE
Generated shortcuts are invalid

### ISSUE THREAD

**Issue by MichaelBrunn3r** [nix-community/plasma-manager#304]
This shortcut ...
```nix
programs.plasma.shortcuts = {
      "kwin"."Window Move" = "Meta+G,,Move Window";
};
```
... generates this line in `kglobalshortcutsrc`:
```config
Window Move=Meta+G\\,\\,Move Window,,
```

Not only are there invalid (?) `\\`, but also 2 trailing `,`. Upon restarting the computer, this invalid line will be reset to its default.

In contrast, generating the shortcut like this ...
```nix
programs.plasma.configFile.kglobalshortcutsrc = {
  kwin."Window Move".value = "Meta+G,,Move Window";
};
```
... generates a valid line, which KDE accepts:
```config
Window Move=Meta+G,,Move Window
```

Am I missing something or is this a bug?

**Comment by magnouvean** [comment]
plasma-manager doesn't really support adding the description for keybindings (at least for now). Setting `"kwin"."Window Move" = "Meta+G";`  should work (that's what it expects). Maybe some more options for setting the descriptions will come in the future, but it isn't really the biggest priority.

**Comment by MichaelBrunn3r** [comment]
Oh, I thought `Meta+G,Alt+G,Move Window` stood for `<shortcut>,<default>,<description>`.
`programs.plasma.shortcuts."kwin"."Window Move" = "Meta+G"` does not work for me. It sets the line in `kglobalshortcutsrc` to `Window Move = Meta+G'.
Upon restarting the computer all shortcuts are reset to their default :/

**Comment by MichaelBrunn3r** [comment]
Oh, I didn't know that information was optional and contained e.g. the default value. Your suggestion works for me, I don't have a need for descriptions for now.

Thx for the help
