### ISSUE TITLE
Support for configuring only through plasma-manager

### ISSUE THREAD

**Issue by magnouvean** [nix-community/plasma-manager#32]
At the moment when configuring kde plasma through plasma-manager it only really modifies the configurations specified, so if there are any other options they can be configured through the gui. This is all good and we should keep this an option, but one thing which would be nice is if we had a way so that only the settings specified from plasma-manager would be set, and all others kept as the defaults. This then would be much more consistent across different systems, as then effectively all the settings would be the same (at least functionality-wise). This should hopefully be possible by resetting the settings before running the kwriteconfig commands. The idea which I think this could be done would be to add an option which could be disabled by default (I think this probably makes the most sense), which if enabled does as specified above.

**Comment by toast003** [comment]
I'll see what I can do

**Comment by magnouvean** [comment]
Good :). Looking online it seems like there isn't any way to reset all the stuff from the command-line, but an idea is to just remove the config-files already present before applying the configurations using kwriteconfig5 and then when logging back in to kde it should have the desired effect. I might try this out and see if it works.

**Comment by magnouvean** [comment]
I tried this approach out in https://github.com/magnouvean/plasma-manager, and honestly it worked better than expected. Initially this seems to solve exactly what I intended here, with only one small problem with theming. I'll test a little bit out further in the coming week or so, and if no major problems appear within then I'll probably merge this solution quite soon, unless anyone can come up with a better idea.

**Comment by toast003** [comment]
Looks good to me, although the description feels a bit weird to me

**Comment by toast003** [comment]
Also it might be a good idea to rename the option to something like `overrideConfig`, kinda like `services.syncthing.overrideFolders` and `services.syncthing.overrideDevices` on NixOS

**Comment by magnouvean** [comment]
Thanks @toast003 for both the suggestions. I just forgot to check over the description, I will fix both of these before merging.
