### ISSUE TITLE
Options "workspace" & "panels" aren't working.

### ISSUE THREAD

**Issue by tye-exe** [nix-community/plasma-manager#348]
The "workspace" & "panel" configurations aren't working for my configuration, i believe that this is an issue with plasma-manager itself, since the "startup" & "hotkeys" are working. Furthermore, this issue is happening to me across three different machines, including one with a fresh install of nixos 24.05.
However, if I'm doing anything wrong then I'd love to hear what it is.

Relevant files/links:
- [flake.nix](https://github.com/tye-exe/nixos-config/blob/a80dc51eacf6f326b78b1612d1af8ef54feb3bb2/flake.nix)
- [plasma-manager configuration](https://github.com/tye-exe/nixos-config/blob/a80dc51eacf6f326b78b1612d1af8ef54feb3bb2/home/preset/plasma.nix)
- [full configuration](https://github.com/tye-exe/nixos-config/blob/a80dc51eacf6f326b78b1612d1af8ef54feb3bb2)

If anyone wants to try replicate this issue install instructions can be found in the README.md file in the full configuration root (note: these aren't tied to the version of the repo linked here, so any changes to the repo will be present when installing with it).

**Comment by HeitorAugustoLN** [comment]
Have you tried logging out of your session after setting these options?

**Comment by tye-exe** [comment]
Both logging out and/or rebooting have no effect on the "workspace" & "panel" configurations.

**Comment by HeitorAugustoLN** [comment]
Found out that removing syncthingtray script, fixes the problem

**Comment by HeitorAugustoLN** [comment]
It is probably due to the script not having an end

**Comment by tye-exe** [comment]
do you mean that the package syncthingtray is causing the issue?

**Comment by tye-exe** [comment]
oh my bad, i understand what you mean

**Comment by HeitorAugustoLN** [comment]
You can still run this script, but you need to put in a lower priority

**Comment by HeitorAugustoLN** [comment]
So others scripts can run before that

**Comment by HeitorAugustoLN** [comment]
```nix
startup.startupScript."start_syncthing" = {
  text = "syncthing; syncthingtray";
  priority = 4;
};
```

**Comment by tye-exe** [comment]
would it be fixed by putting a ";" after "syncthingtray". Ending up looking like "syncthing; syncthingtray;"?

**Comment by tye-exe** [comment]
or do i have to use " &>> /dev/null" to redirect the output & start it in the background?

**Comment by tye-exe** [comment]
I can do more testing on it later as i'm busy rn. But thank you for telling me the answer, i was stumped.

**Comment by HeitorAugustoLN** [comment]
> would it be fixed by putting a ";" after "syncthingtray". Ending up looking like "syncthing; syncthingtray;"?

This doesn't work

**Comment by HeitorAugustoLN** [comment]
> or do i have to use " &>> /dev/null" to redirect the output & start it in the background?

This works too

**Comment by tye-exe** [comment]
thank you very much!

**Comment by tye-exe** [comment]
To anyone reading this in the future; I found the "startup.startupScript" option to be a tad unreliable. So i am using systemd with home manager to execute scripts/commands instead.

I found these two articles to be very useful in figure out how to do this:
- https://linuxhandbook.com/create-systemd-services/
- https://haseebmajid.dev/posts/2023-10-08-how-to-create-systemd-services-in-nix-home-manager/

Alongside [home-manager-options](https://home-manager-options.extranix.com/?query=systemd&release=release-24.05).

---

This is what i have in my home-manager configuration to start syncthingtray when all the system initialization is completed:
```nix
  systemd.user = {
    enable = true;
    startServices = "sd-switch";

    services.syncthingtray-start = {
      Unit.Description = "Starts syncthingtray.";
      Install.WantedBy = [ "default.target" ];

      Service = {
        ExecStart = "${pkgs.writeShellScript "syncthingtray-start" ''
          #!${pkgs.bash}/bin/bash
          ${pkgs.syncthingtray}/bin/syncthingtray --wait''}";
        Restart = "on-failure";
      };
    };
  };
```
