### ISSUE TITLE
Escaping `[]`

### ISSUE THREAD

**Issue by haizaar** [nix-community/plasma-manager#35]
Good day,

I have the following configuration I want to apply under `programs.plasma.configFile`:
```nix
        "kwinrc"."Wayland"."InputMethod[$e]" = "/run/current-system/sw/share/applications/com.github.maliit.keyboard.desktop";
```

which results in the following broken configuration however in `kwinrc`
```desktop
[Wayland]
InputMethod\x5b$e\x5d=/run/current-system/sw/share/applications/com.github.maliit.keyboard.desktop
```

Is there a way to escape `[]` or is it a plasma-manager bug?

**Comment by magnouvean** [comment]
I am pretty sure this is a kwriteconfig bug, which is what we are using at the moment as this is bundled with kde. We probably should change this method though as this tool is quite limited. I assume that if you run:
```
kwriteconfig5 --file kwinrc --group Wayland --key 'InputMethod[$e]' "/run/current-system/sw/share/applications/com.github.maliit.keyboard.desktop"
```
or
```
kwriteconfig5 --file kwinrc --group Wayland --key 'InputMethod\[$e\]' "/run/current-system/sw/share/applications/com.github.maliit.keyboard.desktop"
```
you get similar results? If this doesn't work it is a kwriteconfig issue (and also a plasma-manager issue). Kwriteconfig is quite limited in this regard. We probably should write our own little tool for this with some simple python-script or something.

**Comment by toast003** [comment]
You can do this and I'll bring you closer
```
programs.plasma = {
	enable = true;
	configFile = {
		"kwinrc" = {
			"Wayland" = {
				"InputMethod" = "/run/current-system/sw/share/applications/com.github.maliit.keyboard.desktop";
				configGroupNesting = [ "Wayland" "$e" ];
			};
		};
	};
};
```
However, even if the script does do everything just fine kwriteconfig seemss to be bugged since it writes this to kwinrc
```
[Wayland][\x24e]
InputMethod=/run/current-system/sw/share/applications/com.github.maliit.keyboard.desktop
```

**Comment by haizaar** [comment]
Thank you for the quick response guys. After playing with it further I found out that the `[$e]` part is not essential - the configuration works find without it, at list in my particular use case.

I think it's still a bug (somewhere down the chain) but at there is a workaround, sort of.

**Comment by toast003** [comment]
We could be kinda hacky and just replace \x24 with $ after running kwriteconfig, but only as temporary thing until we do #1

**Comment by magnouvean** [comment]
That would probably work just fine and is a clever solution, though I don't actually think that solving #1 would necessarily be very difficult given how limited kwriteconfig5 actually is. We probably could replace it with a small python-script or something, so I can probably get it done by the end of the year for sure.

**Comment by toast003** [comment]
Maybe, I would jump in and try to replace kwriteconfig myself, but what I'm learning rn (java and c#) isn't ideal since I don't think we want to depend on mono or a jre.

I would prefer if I was learning something else (looking at rust and/or go rn) but I don't want to end up trying to do too much at once and getting burnt out

**Comment by magnouvean** [comment]
Rust could work (I know the language at least), the only problem with that would be that we would have to pull in the compiler and whatnot for such a small script. Python I reckon is less problematic as it is widely used for this sort of stuff and probably installed on most systems anyway. Anyway I reckon I'll try to come up with a quick python-script which takes care of all this for us and fixes the [$e]-problem and adds the other requirements as well, it probably won't take long, so we don't need to implement the solution above. We can reconsider it if something unexpected appears that will delay this process.

**Comment by haizaar** [comment]
My 2 cents:

* `script/rc2nix.rb` is using Ruby. It will be an overkill to have a different language for each script. If you plan to use Python for a config writer script, I would suggest converting `rc2nix.rb` into Python as well.
* I'm not a nix pro, but maybe something like making plasma-manager available to through nixpkgs (or `plasma-manager-tools`?) will bump the usability for the end user where they:
  * Use `plasma-manager` as a flake/module to apply the configuration
  * Install `plasma-manager-tools` to get access to rc2nix, etc. - that is, without cloning the code and pulling in ruby runtime as they have to today

**Comment by magnouvean** [comment]
Yes I agree with the ruby part. I don't know ruby at all, and I reckon it would be better to have it in python. Lately `rc2nix` hasn't really been that much of a priority as extending other features has been prioritized, but after a while it probably will be rewritten in some way. As for having it in nixpkgs I reckon the rc2nix could potentially end up there in for example a `plasma-manager-tools` package, though with the ordinary `plasma-manager` being flake-based I am not sure if it makes sense to add it to nixpkgs (maybe the config writing script however). Most people use `home-manager` from a tarball/flake and since this builds on top of `home-manager` I reckon it is fine this remains mostly flake-based.

**Comment by toast003** [comment]
(Not quite sure of what you mean,  I'll assume you're suggesting splitting rc2nix from plasma-manager itself)
Wouldn't mind that but I don't really see the point?

True, splitting it now will make plasma-manager not pull in Ruby ( although iirc some NixOS activation scripts still use Ruby, so you might have it anyways. Not sure ), although when it gets rewritten into Python that won't be an issue anymore.


> I would suggest converting `rc2nix.rb` into Python as well.

Good idea imo considering rc2nix has some problems rn (just look at issues https://github.com/pjones/plasma-manager/issues/17 and https://github.com/pjones/plasma-manager/issues/15 for example)

**Comment by haizaar** [comment]
Well, I'm not on the flake bandwago yet, so I'm using plasma-manager as follows:
```nix
{ config, pkgs, ... }:

let
  plasma-manager = pkgs.fetchFromGitHub {
    owner = "pjones";
    repo = "plasma-manager";
    rev = "019a8fd22a26c8d59f63aa9cc8a9c1729d6ffbda";
    sha256 = "sha256-1ke+7xrkCVOI13RJ1w6EjCGcJywkN3bbTKbLWAt4jaE";
  } + "/modules";

in
{

  ...

  home-manager.users.haizaar = { config, pkgs, ... }: {

    imports = [
      plasma-manager
    ];

    programs.plasma = {
      ...
    }
  }
}
```

Which leaves me without rc2nix tool readily available. To use it, I need to clone repo and ensure I have whatever runtime is needed to run it (with language package dependencies, etc.). My point is that if it was available through `nix-shell -p rc2nix` it would've made it much smoother user experience.

**Comment by toast003** [comment]
Makes sense
That's something we could eventually do, although it (and rc2nix in general) isn't very high priority

In case you didn't know you don't need to use flakes in your NixOS config to use flakes, as long as you enable flakes on nix itself you can run rc2nix as everyone else does without any issues

**Comment by haizaar** [comment]
> In case you didn't know you don't need to use flakes in your NixOS config to use flakes, as long as you enable flakes on nix itself you can run rc2nix as everyone else does without any issues

For nix novices like myself, an example on how to do it (e.g. in README.md) would really help.

**Comment by toast003** [comment]
Issue seems to be fixed by #39, so we'll close this issue whenever it gets merged

**Comment by magnouvean** [comment]
Should be fixed now as I just merged #39. Feel free to reopen if any issues still occur :)

**Comment by CHN-beta** [comment]
I wonder how should I escape `[]` properly with the last plasma manager.

I tried
```nix
configFile.Wayland."InputMethod\\[\\$e\\]".value = "/run/current-system/sw/share/applications/fcitx5-wayland-launcher.desktop";
```
got
```conf
[Wayland]
InputMethod=/run/current-system/sw/share/applications/fcitx5-wayland-launcher.desktop
```

**Comment by CHN-beta** [comment]
> I wonder how should I escape `[]` properly with the last plasma manager.
> 
> I tried
> 
> ```nix
> configFile.Wayland."InputMethod\\[\\$e\\]".value = "/run/current-system/sw/share/applications/fcitx5-wayland-launcher.desktop";
> ```
> 
> got
> 
> ```
> [Wayland]
> InputMethod=/run/current-system/sw/share/applications/fcitx5-wayland-launcher.desktop
> ```

I see, use this:
```nix
configFile.Wayland."InputMethod" =
{
  value = "/run/current-system/sw/share/applications/fcitx5-wayland-launcher.desktop";
  shellExpand = true;
};
```
