### ISSUE TITLE
Enabling polonium causes error

### ISSUE THREAD

**Issue by Dopplerian** [nix-community/plasma-manager#385]
When I try to set `programs.plasma.kwin.scripts.polonium = true;` and then do `home-manager switch`, I get an error saying 'undefined variable polonium' pointing to line 629 in `modules/kwin.nix`:

~~~nix
      home.packages = with pkgs; [ ] ++ optionals (cfg.kwin.scripts.polonium.enable == true) [ polonium ];
~~~

I'm pretty sure it should say `libsForQt5.polonium` instead of just `polonium` there at the end, since that is the actual name of the package, but I lack the Nix expertise to properly check it.

**Comment by HeitorAugustoLN** [comment]
Currently plasma-manager only have a unstable branch, so we only keep track of changes in nixpkgs unstable, and `polonium` is what currently is on nixpkgs unstable. We are going to start providing a stable release branch when NixOS 24.11 is released. To fix this problem, you can create an alias with an overlay in home-manager:
```nix
{
  nixpkgs.overlays = [
    (final: prev: {
      polonium = prev.libsForQt5.polonium;
    })
  ];
}

**Comment by Dopplerian** [comment]
I hadn't considered the unstable channel. This works nicely.

Thank you, specially for the quick response!
