### ISSUE TITLE
kickoff widget button options incomplete

### ISSUE THREAD

**Issue by StrangeGirlMurph** [nix-community/plasma-manager#394]
Playing around with the kickoff widget in a panel I noticed that a matching `systemFavorites=lock-screen\\,logout\\,save-session\\,switch-user\\,suspend\\,hibernate\\,reboot\\,shutdown` for powerAndSession and `systemFavorites=lock-screen\\,logout\\,save-session\\,switch-user` for session is missing in the `plasma-org.kde.plasma.desktop-appletsrc` is missing.

https://github.com/nix-community/plasma-manager/blob/154ec91cc626269d078931877eb9c141bb0e837b/modules/widgets/kickoff.nix#L117-L132

These manual settings

![image](https://github.com/user-attachments/assets/5023bc04-9000-41fb-83fa-349f4057639e)

create this config

```
[Containments][89][Applets][90][Configuration][General]
alphaSort=true
applicationsDisplay=1
favoritesDisplay=0
favoritesPortedToKAstats=true
icon=nix-snowflake
paneSwap=false
primaryActions=3
showActionButtonCaptions=false
systemFavorites=lock-screen\\,logout\\,save-session\\,switch-user\\,suspend\\,hibernate\\,reboot\\,shutdown
```

When setting everything with plasma-manager the systemFavorites option is missing and therefore with 
```
          kickoff = {
            icon = "nix-snowflake-white";
            sortAlphabetically = true;
            sidebarPosition = "left";
            favoritesDisplayMode = "grid";
            applicationsDisplayMode = "list";
            showButtonsFor = "powerAndSession";
            showActionButtonCaptions = false;
          };
```

only the default power options are shown.

**Comment by HeitorAugustoLN** [comment]
Should be fixed now :)

**Comment by StrangeGirlMurph** [comment]
Thanks :)
