### ISSUE TITLE
Using kde theme settings to be deployed by plasma-manager module

### ISSUE THREAD

**Issue by D3vil0p3r** [nix-community/plasma-manager#40]
Hello, I just discovered this module since among official home-manager modules I don't see plasma-manager that seems cool to make it official.

Usually, to set theme config on my KDE environment I use the following CLI commands to set theme, icons, cursor and background:
```sh
plasma-apply-lookandfeel -a org.kde.breezedark.desktop # It applies Plasma Global Theme and Color Scheme too
    
dbus-send --session --dest=org.kde.GtkConfig --type=method_call /GtkConfig org.kde.GtkConfig.setGtkTheme "string:$theme_name"
    
/usr/lib/plasma-changeicons "$icon_theme"
    
plasma-apply-cursortheme "$cursor_theme"
    
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "var allDesktops = desktops(); for(i=0; i<allDesktops.length; i++) { myDesktop=allDesktops[i]; print(myDesktop); myDesktop.currentConfigGroup = Array(\"Wallpaper\",\"org.kde.image\",\"General\");var wallpaper = \"$background_theme\"; myDesktop.writeConfig(\"Image\", wallpaper);print(myDesktop.readConfig(\"Image\"));}"
    
kwriteconfig5 --file kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key Image "$background_theme"
```
Can plasma-manager to replicate these KDE configs? If so, how is it possible?

**Comment by magnouvean** [comment]
This should be what the latest version now does (as was implemented in #41). To use this for theming it should be as simple as using the `workspace` set of options, i.e. in your case setting `programs.plasma.workspace.lookAndFeel = "org.kde.breezedark.desktop"`, or other options for your other tasks. Keep in mind that how this works is that it creates an autostart script which runs something like the commands above on startup, so you will need to log back in to see the changes take effect. I plan to run this script immediately if plasma is running in the future, I just haven't gotten there yet. There also exists options for wallpaper and cursortheme, as well as some others (see the README for some examples, and the [workspace.nix](https://github.com/pjones/plasma-manager/blob/trunk/modules/workspace.nix) module for all of the options). Hope this helps you :)

**Comment by magnouvean** [comment]
Also for gtk thing the following should do the trick I think:
```nix
  programs.plasma = {
    configFile = {
      "gtk-3.0/settings.ini"."Settings"."gtk-theme-name" = "$gtk_theme";
      "gtk-4.0/settings.ini"."Settings"."gtk-theme-name" = "$gtk_theme";
    };
  };
```
Where you obviously replace `$gtk_theme` with your desired theme name.

**Comment by toast003** [comment]
You should probably use the built in home manager gtk module https://nix-community.github.io/home-manager/options.xhtml#opt-gtk.theme

**Comment by magnouvean** [comment]
Yeah that is probably a better solution for gtk. Since this is now implemented I reckon we can close this. If you need to run custom commands as well, check out the `startup` module, in particular `autoStartScript` which lets you run the theme commands as you wish before kde is started.
