### ISSUE TITLE
allow users to configure session restore (system settings > startup and shutdown)

### ISSUE THREAD

**Issue by Nowaaru** [nix-community/plasma-manager#402]
i'm tired of closing 20 apps everytime i start a kde session and i can't change it using plasma-manager. that's all

**Comment by HeitorAugustoLN** [comment]
I will make it an option soon :)

**Comment by jdev082** [comment]
In the mean time, is there any way to configure this through the configFile option? I can't seem to find it in the output of rc2nix.

**Comment by NovaViper** [comment]
It's this `ksmserverrc.General.loginMode;` and the possible values are `"restoreSavedSession"`, `"emptySession"`, and `null` (where it just doesn't exist at all)

**Comment by HeitorAugustoLN** [comment]
Sorry for the delay guys, I'm really busy these days, I will create a new module only for session in this weekend (maybe before) that will include this option.
