### ISSUE TITLE
Hibernate on Plasma 6.2

### ISSUE THREAD

**Issue by StrangeGirlMurph** [nix-community/plasma-manager#403]
Somehow plasma doesn't support the hibernate options plasma manager offers for powerdevil.

```nix
batteryLevels = {
        criticalAction = "hibernate";
        criticalLevel = 2;
};
```

Causes these banners to appear.

![image](https://github.com/user-attachments/assets/3df127e1-6b54-4837-9b3a-5c5e45709be9)

Same for any other place where I selected hibernate

![image](https://github.com/user-attachments/assets/b1b56ac6-7b81-4a59-8811-a74b33acb0df)

The drop-down tells me hibernate just isn't an option (anymore).

**Comment by StrangeGirlMurph** [comment]
Wait I think this might just be a hardware or my OS thing. Sorry. Will close this for now

**Comment by HeitorAugustoLN** [comment]
Hibernate is disabled depending on what is enabled in nixos modules. You probably enabled something like `security.protectKernelImage` and that disables hibernation. Or something that adds `nohibernate` in kernelParams

https://github.com/NixOS/nixpkgs/blob/89172919243df199fe237ba0f776c3e3e3d72367/nixos/modules/security/misc.nix#L123
