### ISSUE TITLE
Default Applications

### ISSUE THREAD

**Issue by onnyyonn** [nix-community/plasma-manager#406]
Is it possible to set the default applications (Such as terminal, text editor etc.) from Plasma Manager? If not, please consider adding these options.

**Comment by magnouvean** [comment]
I think kde relies on xdg-mime for this task, so it should be configured through `home-manager` instead which has support for this (through `xdg.mimeApps`). If there are apps which aren't covered in this we could consider adding support for this :)

**Comment by HeitorAugustoLN** [comment]
I will be closing this since this are not in the scope of plasma-manager.
This should be set using home-manager `xdg.mimeApps`.
You can see what KDE Plasma changes in `$XDG_CONFIG_HOME/mimeapps.list`. And then just replicate it in home-manager.
