### ISSUE TITLE
KDE Panels: How to add Floating Widgets?

### ISSUE THREAD

**Issue by k1llerk3ks** [nix-community/plasma-manager#412]
I am successfully defining my KDE widgets in the bars (top,bottom,left,right), but i cannot define a widget on the workspace. Is this meant by "floating" in https://github.com/nix-community/plasma-manager/blob/trunk/modules/panels.nix?

i have no idea how to set this up, can you maybe provide me an example? i can happily add it to the example folder, if i am smarter after :) thx!

**Comment by HeitorAugustoLN** [comment]
"Floating" widgets are set in `programs.plasma.desktop.widgets`. You can see an example in my configuration: https://github.com/HeitorAugustoLN/nix-config/blob/768dc9301227c6daf632fa558a69bf27748b1bea/home/heitor/features/desktop/plasma/theme.nix#L36

The floating panel configuration is to make the painel float
