### ISSUE TITLE
Value range for programs.plasma.kwin.tiling.padding

### ISSUE THREAD

**Issue by alaestor** [nix-community/plasma-manager#417]
I may be mistaken as I'm a a bit of a noob, but while I was converting some outputs from rc2nix I noticed that `padding.tiling` takes non-zero `ints.positive` while Plasma 6's tiling layout editor GUI seems to allow for values [0 - 36]. This should probably be `ints.between 0 36`.

**Comment by HeitorAugustoLN** [comment]
You're right! I will update it soon enough :)
