### ISSUE TITLE
[BUG]: programs.plasma.workspace.cursor.theme doesn't work

### ISSUE THREAD

**Issue by jiriks74** [nix-community/plasma-manager#418]
I've set up a custom theme and set it like so:

```nix
  programs.plasma = {
    workspace = {
      lookAndFeel = "Catppuccin-Mocha-Mauve";
      cursor = {
        theme = "Breeze";
      };
    };
  };
```

The theme gets set but the cursor theme doesn't. It still uses the default set by the theme set in `lookAndFeel` instead of `Breeze`. Or, sometimes, it works for Wayland apps but not for Xorg apps and it's still the theme's default in the settings.

Output of `plasma-apply-cursortheme --list-themes`:

```bash
You have the following mouse cursor themes on your system:
 * Catppuccin-Mocha-Dark [Catppuccin-Mocha-Dark-Cursors]
 * Catppuccin-Mocha-Mauve [Catppuccin-Mocha-Mauve-Cursors] (Current theme for this Plasma session)
 * Breeze [breeze_cursors]
 * Breeze Light [Breeze_Light]
```

**Comment by jiriks74** [comment]
Nevermind, I'm an idiot.

Should've used `breeze_cursors` instead of `Breeze`. It just didn't occur to me until I made this as the other commands output like this:

```bash
$ plasma-apply-lookandfeel --list
Catppuccin-Mocha-Mauve
org.kde.breezedark.desktop
org.kde.breezetwilight.desktop
org.kde.breeze.desktop
```

and you can just use whatever is first on the line you want.

**Comment by cudatuda** [comment]
@jiriks74 doesn't work for me. Cursor theme is inconsistent between Plasma bottom panel (white cursor) and i.e. Chromium (black breeze cursor). When manually setting cursor theme in settings GUI everything works as expected. Any suggestions?

**Comment by jiriks74** [comment]
> Any suggestions?

Post the relevant config and the output of `plasma-apply-cursortheme --list-themes`.

**Comment by cudatuda** [comment]
Output of `plasma-apply-cursortheme --list-themes`:
```
You have the following mouse cursor themes on your system:
 * DMZ (White) [Vanilla-DMZ]
 * Default [default]
 * DMZ (Black) [DMZ-Black]
 * DMZ (White) [DMZ-White]
 * DMZ (Black) [Vanilla-DMZ-AA]
 * Breeze [breeze_cursors] (Current theme for this Plasma session)
 * Breeze Light [Breeze_Light]
```
Relevant plasma manager config:
```
  programs.plasma = {
    enable = true;
    workspace = {
      colorScheme = "BreezeDark";
      lookAndFeel = "org.kde.breezedark.desktop";
      cursor.theme = "breeze_cursors";
    };
  };
```

Also tried setting `programs.dconf.enable = true;` as described [here](https://nixos.wiki/wiki/KDE#GTK_themes_are_not_applied_in_Wayland_applications_.2F_Window_Decorations_missing_.2F_Cursor_looks_differen) - still no luck.

**Comment by jiriks74** [comment]
This *could* be a GTK issue or a Wayland/XWayland issue. Did you try other apps?

**Comment by cudatuda** [comment]
Looks like _stylix_ overrides all cursor settings made by plasma manager. After setting `stylix.cursor.name = "breeze_cursors";` desktop has correct theme, but wrong size. I will investigate this issue, thanks for pointing me in the right direction!

**Comment by HeitorAugustoLN** [comment]
@cudatuda Stylix sometimes conflicts with plasma-manager, I would recommend you to set themes in stylix if you're using it in conjuction with plasma-manager
