### ISSUE TITLE
KDE should respect home-manager default fonts

### ISSUE THREAD

**Issue by Asqiir** [nix-community/plasma-manager#437]
I set some specific fonts as my default-fonts in home-manager:
```nix
    fonts.fontconfig.enable = true;

    fonts.fontconfig.defaultFonts = {
      serif = [ "Noto Serif" ];
      sansSerif = [ "Fira Sans Compressed" ];
      monospace = [ "MonaspiceAr Nerd Font Mono" ]; # the one from konsole or from kate is better?
      emoji = [ "Noto Color Emoji"];
    };
```
When applying and restarting my session, the KDE settings have not applied them (settings window > Text & Fonts > Fonts).
Imo they should be applied automatically, or at least we should provide an opt-out or opt-in option. What is you opinion?

**Comment by HeitorAugustoLN** [comment]
Well, there is not much we can do about it. Since KDE fonts are defined in `kdeglobals`, with the qt format. While these options set fonts in different place with a different format. GNOME and COSMIC also sets fonts in different ways, there is no standard. So the best way is to configure each one separately

**Comment by HeitorAugustoLN** [comment]
But if you want all of them to be the same shouldn't be too hard to do it using a custom module in your configuration or by using `config`

**Comment by Asqiir** [comment]
Hmm.
I would prefer a plasma-manager to (attempt to) install the font in all appropriate places, but maybe that's too hard/impossible.

**Comment by Asqiir** [comment]
Update: the feature I wanted seems to already exist:  `programs.plasma.fonts`
