### ISSUE TITLE
Configuring LibInput devices

### ISSUE THREAD

**Issue by billy4479** [nix-community/plasma-manager#47]
I happen to use natural scrolling and a few other options on my laptop touchpad.
These option are set in `~/.config/kcminputrc` as 

```
[Libinput][10182][480][GXTP7863:00 27C6:01E0 Touchpad]
DisableWhileTyping=false
NaturalScroll=true
TapToClick=true
```

I'd like to use these same settings for any laptop I (will) use.
As you can see the group name is kinda device-specific: for sure the last part (`[GXTP7863:00 27C6:01E0 Touchpad]`) is the name of the input device as it shows in `libinput list-devices`; I still haven't figured out what the other two numbers are (`[10182]` and `[480]`). 

For now I can just hardcode them in my config but I don't think that's the best solution..

If someone manages to figure out what the other two numbers are we could query them at activation-time and have an option to enable or disable such features for any touchpad.

**Comment by toast003** [comment]
Tried finding out what writes the numbers are by reading the [source code for the mouse kcm](https://invent.kde.org/plasma/plasma-desktop/-/tree/master/kcms/mouse) but I haven't gotten anything yet

**Comment by toast003** [comment]
[This repo](https://github.com/MatMoul/plasma-config-matmoul/blob/master/profile/.config/kcminputrc) just puts setting under `[Mouse]` :thinking: 
I'll try it out 
EDIT: Don't think it works anymore (the config file I linked is 8 years old after all), but I'm doing other things so I can't log out or restart plasma, so maybe that's why it doesn't work

**Comment by billy4479** [comment]
> Tried finding out what writes the numbers are by reading the [source code for the mouse kcm](https://invent.kde.org/plasma/plasma-desktop/-/tree/master/kcms/mouse) but I haven't gotten anything yet

Thanks for the link, I'll try to look into it too.

Also, I forgot to add in the original post that I'm using the Wayland session. Maybe the X11 session uses some other config (?), I'll try to login into a X session when I have time and I'll let you know if I find any difference.

**Comment by toast003** [comment]
I'm also using Wayland 

11 Jan 2024, 12:09 pm by ***@***.***:

**Comment by ribru17** [comment]
> If someone manages to figure out what the other two numbers are we could query them at activation-time and have an option to enable or disable such features for any touchpad.

The first two numbers are the decimal representations of the middle (hexadecimal) numbers: e.g., for
`[Libinput][10182][480][GXTP7863:00 27C6:01E0 Touchpad]`:
10182 = 0x27C6
480=0x1E0

**Comment by ChocolateLoverRaj** [comment]
I would like an option to enable reverse scrolling on all touchpads regardless of ID

**Comment by toast003** [comment]
For usb devices the two numbers are the usb id in decimal, and the name is just the name of the device, for i2c devices (touchpads) the two numbers are some sort of id, then the name is the name of the device followed by it's name (how it shows up in /sys/bus/i2c/devices) followed by the id again in hex and then Touchpad

**Comment by ribru17** [comment]
@toast003 So if we specifically want an option for touchpad behavior, we can just `cat /proc/bus/input/devices | grep -i touchpad` and deterministically extract the numbers from just before "Touchpad", using them to index the setting field?

Edit: we can grep the ID with `cat /proc/bus/input/devices | grep -i touchpad | sed 's/N: Name=".* \(.*\) Touchpad"/\1/'`

**Comment by toast003** [comment]
We could do that, although I'm not sure if that's something that should be done in `write_config.py` or a new script

**Comment by ada4a** [comment]
I think this can be closed now?
