### ISSUE TITLE
Per panel widget configuration?

### ISSUE THREAD

**Issue by toast003** [nix-community/plasma-manager#56]
https://github.com/pjones/plasma-manager/pull/54 introduced the [panelModifyConfig](https://github.com/magnouvean/plasma-manager/blob/76f00fe766ea3255bf31055c14cb0df8749c1145/modules/panels.nix#L109) function, and I think we should expose this to be able to have per-panel widget configs

**Comment by toast003** [comment]
Imo the best way to do this would be to have the widgets accept either a string with the widget name, or a submodule with the name and the config for that widget, kinda like this:
``` nix
panels = [
  {
    location = "bottom";
    widgets = [
      {
        name = "org.kde.plasma.kickoff";
        config = {
          General.icon = "nix-snowflake-white";
        };
      }
      "org.kde.plasma.icontasks"
      "org.kde.plasma.marignsseperator"
      "org.kde.plasma.systemtray"
      "org.kde.plasma.digitalclock"
    ]
  }
];

**Comment by noisesfromspace** [comment]
This would be great, I only have one widget I'd like to configure and now every-time my system restarts the widget setting is reset.

**Comment by toast003** [comment]
Sorry for not doing anything about this, I want it too but I have been pretty busy lately

I did remember I was trying to see how I would do this and I managed to get it working with this
```nix
panels = [
  {
    location = "top";
    extraSettings = ''
      for (i = 0; i < panel.widgetIds.length; i++ ) {
        currentWidget = panel.widgetById(panel.widgetIds[i])
        if (currentWidget.type == "org.kde.plasma.kickoff" ) {
          // You can change the config here 
          currentWidget.currentConfigGroup = ["General"]
          currentWidget.writeConfig("icon", "nix-snowflake-white")
        }
      }
    '';
  }
];
```
This is not per panel and changes every widget but I hope it's good enough until I can get back to doing stuff @martijnboers

**Comment by noisesfromspace** [comment]
Ow nice that will work! I noticed that the widget number varies on installs so I'll try this out. No worries about not having time, I might have a jab at implementing something but it's a relatively niche project. All the effort is very welcome

**Comment by magnouvean** [comment]
Do note that the above for-loop should not be neccesary as all the widgets are saved in a `panelWidgets` dictionary, so you should be able to use `currentWidget = panelWidgets["org.kde.plasma.kickoff"]`. That said there a.t.m. is no proper nix interface for the `writeConfig` thing above (I'll see if I can add this in the weekend, as it should be quite a simple tweak).
