### ISSUE TITLE
WidgetConfig

### ISSUE THREAD

**Issue by Svenum** [nix-community/plasma-manager#61]
Hey,
I updated my flake and saw the new "config per widget" option, thats nice. But if I add my launchers to my pannel it dont work. it replaces every "," with an "//,":

should be:
` launchers=applications:org.kde.dolphin.desktop,preferred://browser,applications:com.valvesoftware.Steam.desktop,applications:net.lutris.Lutris.desktop,applications:net.lutris.league-of-legends-1.desktop,applications:org.remmina.Remmina.desktop"`

is actually:
` launchers=applications:org.kde.dolphin.desktop\\,preferred://browser\\,applications:com.valvesoftware.Steam.desktop\\,applications:net.lutris.Lutris.desktop\\,applications:net.lutris.league-of-legends-1.desktop\\,applications:org.remmina.Remmina.desktop `

my code is here:
https://github.com/Svenum/NixOS-Config/blob/plasma-manager/users/sven/plasma.nix

**Comment by magnouvean** [comment]
I think in plasma-scripts the "correct" way of specifying multiple arguments is using a lua-list which we mimic using from a nix-list. You should be able to use nix lists, like:
```nix
          {
            name = "org.kde.plasma.icontasks";
            config = {
              General = {
                launchers = [
                             "applications:org.kde.dolphin.desktop"
                             "preferred://browser"
                             "applications:com.valvesoftware.Steam.desktop"
                             "applications:net.lutris.Lutris.desktop"
                             "applications:net.lutris.league-of-legends-1.desktop"
                             "applications:org.remmina.Remmina.desktop"
               ];
              };
            };
          }
```
This works on my end anyway :).

**Comment by Svenum** [comment]
I am going to try this later. Thanks

**Comment by Svenum** [comment]
Works great thanks. 😀
