### ISSUE TITLE
Duplicated properties?

### ISSUE THREAD

**Issue by drupol** [nix-community/plasma-manager#7]
Hi,

I would like to update my KDE plasma configuration using rc2nix, when I do it, I see that there are duplicated properties, where brackets are respectively replaced with `\x5b` and `\x5d`.

See this on the diff screenshot: 
![image](https://user-images.githubusercontent.com/252042/180368995-3722fb51-2486-487c-bc06-3343bfb12322.png)

Is it normal? Should I ignore that?

**Comment by drupol** [comment]
@pjones Any clue on this?

**Comment by pjones** [comment]
I'm not sure what would cause this.  I think it's harmless but it's on my list of things to investigate.

If I had to guess I'd say it has something to do with shell escaping arguments to kwriteconfig and is related to issue #1.

**Comment by dlip** [comment]
I'm having the same issue. Hopefully this helps: i noticed if i switch to my config without rebooting, then run rc2nix i get these escape characters. If i then reboot and run rc2nix, it is ok.

**Comment by magnouvean** [comment]
This is very likely fixed now (it probably was due to the fact that `kwriteconfig5` had problems writing some symbols, and we don't use that tool anymore). Feel free to reopen if anyone still think this is an issue.
