### ISSUE TITLE
Can't add shortcut for plasma-pass widget

### ISSUE THREAD

**Issue by FF-AntiK** [nix-community/plasma-manager#74]
Unfortunately `rc2nix` doesn't export the shortcut setting at all.
I looked into `.config/kglobalshortcutsrc` and found the applied shortcut setting:

```
[plasmashell]
...
activate widget 20=Meta+A,none,Activate Plasma Pass Widget
...
```

So I tried to add following nix configuration:

```
plasma = {
  enable = true;
  shortcuts."plasmashell"."activate widget 20" = "Meta+A";
};
```

this creates the following line in `kglobalshortcutsrc`:
`activate widget 20=Meta+A,none,`

But the shortcut isn't working. Is it possible to make it work?

**Comment by magnouvean** [comment]
Yeah `rc2nix` hasn't been updated in a while, so there may be some problems with it. I assume you have tried to log in/out (this is essentially required for most things to be applied in plasma-manager)? If that is not the problem my guess is that widget nr. 20 changes and then widget 20 doesn't refer to plasma-pass anymore. I assume the line is in the correct section as well? I am not aware of a good way to fix this a.t.m. if none of those are the problem.

**Comment by FF-AntiK** [comment]
I always rebootet to test my config.
When I set the shortcut via UI the added line in `kglobalshortcutsrc` still says `widget 20`.
The only difference from the line that `plasma-manager` creates is the description in the end:
`Activate Plasma Pass Widget`

I already tried to delete the shortcut in the UI and then manually add the correct line to `kglobalshortcutsrc`.
Unfortunately this also doesn't work.
Maybe there is another plasma config, which needs to have a definition of what `widget 20` actually refers to?

EDIT: yes I added the line to the correct section. I didn't check yet, if maybe the settings inside the section must be in the right order. I will test if the order makes any difference as soon as I have time.

**Comment by magnouvean** [comment]
The ordering shouldn't matter, and I'd be very suprised if the description has any effect either. One thing to check could be if you add the keybinding manually again via some gui if the same setting is set in the file or if it has changed.

**Comment by FF-AntiK** [comment]
I now found out that I also need this in `plasma-org.kde.plasma.desktop-appletsrc`:
```
[Containments][8][Applets][20][Shortcuts]
global=Meta+A
```
It works when I edit the file manually.
Is there a way to add the lines with `plasma-manager`?

**Comment by magnouvean** [comment]
It depends on how much you want to be configured using `plasma-manager`. There is a way to declaratively set the [panel](https://github.com/pjones/plasma-manager/blob/trunk/modules/panels.nix) (I assume this widget is connected to the panel in some way). This is really the only proper way of configuring panels through `plasma-manager` imo as the `plasma-org.kde.plasma.desktop-appletsrc` changes all the time and may be different between different machines. This is not captured by `rc2nix` as `rc2nix` hasn't really been updated in a while and hasn't been much priority lately (it probably will get some updates eventually), hence why this wasn't added to your config automatically. I am not sure if setting shortcuts in this module is properly supported yet though (I know other types of configurations is) so there may not be support for this yet. If setting bindings is supported through [plasma-scripts](https://develop.kde.org/docs/plasma/scripting/) it may be possible by specifying some lines in `extraSettings` of the panel. This quickly can become complicated though. I can see if there is support for this though, but it might take some time as I am a little busy in the nearest future.

**Comment by magnouvean** [comment]
Just setting the line should also be able to be done using out low-level interface, i.e. something like
```{nix}
configFile."plasma-org.kde.plasma.desktop-appletsrc"."Containments.8.Applets.20.Shortcuts"."global" = "Meta+A";
```

**Comment by FF-AntiK** [comment]
That worked! Thank you very much!

**Comment by FF-AntiK** [comment]
No it did not! =D
When using the `panels` option of `plasma-manager` a new panel will be created at every login, right?
Whenever this happens, all the widgets in the panel get re-registered in `plasma-org.kde.plasma.desktop-appletsrc`.
And by re-registering I mean, that the old entries will stay in the file, and the new ones (with new widget numbers) will be appended. So, if my observation is correct, this means, that the file will grow on every new login.

Should I open another issue for this?

**Comment by magnouvean** [comment]
Hmm, I have seen some oddities when it comes to that and the panel module, but I haven't realized what could be the reason for that. You are probably correct. I think it belongs in a separate issue though so feel free to open one
