### ISSUE TITLE
"nix run github:pjones/plasma-manager" -> error in most recent KDE neon

### ISSUE THREAD

**Issue by novoid** [nix-community/plasma-manager#83]
Hi,

I'm new to Nix(OS) and I'm evaluating other options to my long-runner xfce such as KDE. In order to avoid issues I have with xfce (can't control most settings within HomeManager), I happily found this repository which seems to be a potential answer to my questions on how to control my desktop environment using Nix/HM.

For testing the process starting with `rc2nix`, I set up a fresh KDE neon qemu VM running Plasma 6.

I installed Nix using `sh <(curl -L https://nixos.org/nix/install) --daemon` as instructed on https://nixos.org/download.html

In the VM, (and after a reboot) I then get:

```
vk@kdeneon:~$ nix run github:pjones/plasma-manager
error: experimental Nix feature 'nix-command' is disabled; add '--extra-experimental-features nix-command' to enable it

vk@kdeneon:~$ nix --extra-experimental-features run github:pjones/plasma-manager
warning: unknown experimental feature 'run'
error: 'github:pjones/plasma-manager' is not a recognised command
Try 'nix --help' for more information.

vk@kdeneon:~$ 
``` 

I'm pretty sure it's **not an issue with plasma-manager** but rather my poor knowledge of using Nix. However, I think that my approach might be a very common approach to test your tool by Nix newbies. So you might extend the README with the "fix" for this issue to support those newcomers as well?

Thanks for your help!

**Comment by traverseda** [comment]
nix-command is the feature flag. So

```
nix --extra-experimental-features nix-command run github:pjones/plasma-manager
``` 

You may also need to add the "flake" experiment feature, I'm not sure

**Comment by novoid** [comment]
Yes, I had to use that:

```
nix --extra-experimental-features nix-command --extra-experimental-features flakes run github:pjones/plasma-manager
```

You may want to mention that in the README.

Thanks for your quick help!
