### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by igorcafe** [nix-community/plasma-manager#84]
Sorry for the noobness, but could you provide an example of how to integrate it with home manager?

**Comment by FF-AntiK** [comment]
You can find an example [here](https://github.com/pjones/plasma-manager/tree/trunk/example).

**Comment by Asqiir** [comment]
@igoracmelo If you think anything specific in terms of an example is missing I can try to come up with one.

**Comment by igorcafe** [comment]
@FF-AntiK @Asqiir how can I use it without flakes?

**Comment by dvaerum** [comment]
I am new to Nix(OS) and home-manager, but I think the example code is outdated?

From what I can see here: https://nix-community.github.io/home-manager/release-notes.xhtml#sec-release-22.11-highlights

Something like `extraModules` does not exist in the newer versions of home-manager.

**Comment by Xyz00777** [comment]
> @igoracmelo If you think anything specific in terms of an example is missing I can try to come up with one.

how can i implement the channel directly into my homeassistant/nix config?
i have done it with home assistant like these in my /etc/nixos/configuration.nix:

```
{ config, pkgs, lib, ... }:

let
  home-manager = builtins.fetchTarball "https://github.com/nix-community/home-manager/archive/master.tar.gz";
in
{
  imports =
    [ # Include the results of the hardware scan.
      (import "${home-manager}/nixos")
      ./hardware-configuration.nix
    ];

  # Home manager
  home-manager.users.xyz00777 = {
    imports = [
      ./homemanager/home.nix
    ];
  };

````

i also tried it the same way for plasma-manager but i didnt got it to work. In my opinion these is mutch nicer because when i have to setup my system again i dont have to think about adding the correct channel because these would do it more or less automaticly

**Comment by igorcafe** [comment]
Guys, I haven't used the project and I don't plan to use it in the near future.
Feel free to close this whenever you are done :)

**Comment by magnouvean** [comment]
Sorry for late response. The [getting started section in the README](https://github.com/pjones/plasma-manager/?tab=readme-ov-file#getting-started) offers some help in usage, mainly through examples.

Especially for home-manager setups without flakes I can recommend [the example directory for this](https://github.com/pjones/plasma-manager/tree/trunk/examples/homeManager) (it even includes some instructions), while for flake-based setups there are also a couple examples (see the getting started section).

I'll close this now, but if there are any problems related to these examples feel free to open a separate issue regarding this.
