### ISSUE TITLE
Allow immutable properties

### ISSUE THREAD

**Issue by Noodlez1232** [nix-community/plasma-manager#89]
KDE allows immutability of most settings, which would be good to add to this (e.g. for deployments of a KDE desktop using home-manager). This is done by adding `[$i]` to the section header (e.g. `[KDE][$i]`) to make all the values in that section immutable.

I suggest doing this by adding this type of setting:
```nix
programs.plasma.configFile.kdedrc5.Module-device_automounter = {
   _immutable = true;
   autoload = false;
};
```

In writeConfig, you can add the `[$i]` to the end of the section header for this section.

I'm not 100% sure how writeConfig works (especially the python script), but I imagine it wouldn't be too difficult.

**Comment by magnouvean** [comment]
Nice suggestion. I have thought about it before, it just was a little much work at the time seeing as adding "[$i]" already worked, but I do agree this is a better way of doing this. I will probably implement this once we get some other things out of the way (of course prs are welcome too)!
