### ISSUE TITLE
plasma-manager isnt working with my flake.nix

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [nix-community/plasma-manager#91]
`{
  description = "Home Manager configuration of root";

  inputs = {

    plasma-manager.url = "github:pjones/plasma-manager";
    plasma-manager.inputs.nixpkgs.follows = "nixpkgs";
    plasma-manager.inputs.home-manager.follows = "home-manager";
    nix-software-center.url = "github:snowfallorg/nix-software-center";
    arion.url = "github:hercules-ci/arion";
    arion.inputs.nixpkgs.follows = "nixpkgs";    
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    nix-flatpak.url = "github:gmodena/nix-flatpak"; 
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs@{ 

        self, 
        nixpkgs, 
        arion, 
        home-manager, 
        nix-flatpak, 
        plasma-manager, 
     ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
    in {

      nixosConfigurations.daspidercave = nixpkgs.lib.nixosSystem {
        inherit system;

        modules = [
          ./configuration.nix  
           home-manager.nixosModules.home-manager
           plasma-manager.nixosModules.plasma-manager   

                 {
              home-manager.extraSpecialArgs = { inherit inputs; }; 
              home-manager.users."spiderunderurbed" = { pkgs, ... }: {
              home.stateVersion = "22.11";
              programs.plasma = {
                  enable = true;
                  workspace = {

                        clickItemTo = "select";

                        wallpaper = "/etc/nixos/wallpapers/test.jpg";

                     };
                 };
             imports = [ 
                (plasma-manager + "/modules")

              ];

            };

            }

          nix-flatpak.nixosModules.nix-flatpak
          ./flatpak.nix

          {

             programs.gnupg.agent.pinentryPackage = pkgs.lib.mkForce pkgs.pinentry-qt;

          }
        ];
      };
    };
}`
The title is pretty self explanitory, nixos-rebuild switch --impure works, so does home-manager switch, but there is no indication if plasma manager is working, i set the wallpaper but its not applying.

**Comment by magnouvean** [comment]
Wallpapers need to re-log back in for them to apply. If that doesn't solve it are there files present in `.local/share/plasma-manager`?

**Comment by magnouvean** [comment]
Besides inside home-manager the line
```
imports = [(plasma-manager + "/modules")]
```
Is a little odd maybe? How I have it working is using:
```
home-manager.sharedModules = [ plasma-manager.homeManagerModules.plasma-manager ];
```
See [my flake](https://codeberg.org/magnouvean/nixos-configs/src/commit/a01afa7a6a710c9bc5ec2039731e1eb76cfbd61d/flake.nix) if you want more inspiration about how I do it.

**Comment by SpiderUnderUrBed** [comment]
Ah, it was the sharedModules, putting my file import and module imports in there solved everything
